### ISSUE TITLE
Some terms have the same cell_set_preferred_alias in single taxonomy 

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#102]
![image](https://user-images.githubusercontent.com/112839/121918635-2a7da880-cd2e-11eb-8307-409c4e181d93.png)

L5 IT_2 | n74 | RNAseq 063-064 | CS202002013_190
-- | -- | -- | --
L5 IT_2 | L5 IT_2 | RNAseq 064 | CS202002013_64
-- | -- | -- | --

@jeremymiller  to check origin of these - propose new naming scheme.

**Comment by dosumis** [comment]
@shawntanzk  - assume fixed in latest.  Please check and close if it is.

**Comment by shawntanzk** [comment]
@dosumis it is fixed with new spreadsheet, but we dont have 'cell_set_accession' fixed yet (have already requested @jeremymiller to provide) so that fix is not complete - will close this once that is done

**Comment by dosumis** [comment]
Can you remind me what the problem is with accessions?

**Comment by shawntanzk** [comment]
> Can you remind me what the problem is with accessions?

oh nothing wrong per se, I just need the new 'cell_set_accession' from @jeremymiller - see my comment in #148

**Comment by shawntanzk** [comment]
fixed with https://github.com/obophenotype/brain_data_standards_ontologies/commit/151b7569c948b51d2a4b092eeace982a70014c48
