### ISSUE TITLE
Write script to harvest mappings between cross-species dendrogram and species specific dendrograms

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#104]
SPEC (STATUS DRAFT):

- Take all cell_set_preferred_alias(es) from cross-species taxonomy.  
- In single-species taxonomies, match these strings to the contents of the cell_set_aligned_alias column and if not found to one of the terms in the contents of  cell_set_additional_alias column (multiple terms in these columns are separated by a `|`)
- Use the matches to generate a robot template generating subclassOf relationships between the cell types corresponding to each node: 'species specific' subClassOf 'cross species'

@jeremymiller - please review.   We were a bit confused when we first looked at this, but it seems like we need to use 'cell_set_additional_alias' to map leaf nodes between cross-species taxonomy and single species, aligned_alias is reserved for mappings between more abstract classes.  Is this correct?

**Comment by jeremymiller** [comment]
This is correct.  Cross species "type X" term in cell_set_preferred_alias can be considered a parent of single species "type x" term found in cell_set_additional_alias.

For cell_set_aligned_aligned alias, any node in any taxonomy with that tag should be considered a child or equivalence class of the more generic aligned alias term.  For example, likely every taxonomy will have a "Glutamateric neuron" cell set, which all will be considered glutamatergic neurons (however you decide to code that).

**Comment by dosumis** [comment]
@shawntanzk  - cherry pick some examples for mockups - using the mapping as described above.

Mockups needed for breakout on ontology review + breakout on uses - showing up as cross-species parent class in cell-type card.

**Comment by shawntanzk** [comment]
For implementation of cross-species taxonomy: 
1) Build cross species taxonomy from https://github.com/obophenotype/brain_data_standards_ontologies/blob/single_dosdp_template/src/dendrograms/nomenclature_table_CCN202002270.csv 
2) cell_set_aligned_alias from mouse/human/marmoset should be subclass_of same name from cell_set_aligned_alias in cross-species
3) cell_set_preferred_alias in cross species should be matched with cell_set_additional_alias in mouse/human/marmoset, and mouse/human/marmoset should also be subclass_of same name in cross species (this might at times duplicate mappings in aligned alias)

**Comment by hkir-dev** [comment]
Initial version of the cross-species ontology is at: https://github.com/obophenotype/brain_data_standards_ontologies/blob/cross_species/bdscratch-full.owl

**Comment by shawntanzk** [comment]
done and looks good
