### ISSUE TITLE
Cross species dendrogram

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#106]
We do not currently have the cross-species dendrogram on this repo.  Please add it here: https://github.com/obophenotype/brain_data_standards_ontologies/tree/ec_individuals/src/dendrograms

**Comment by jeremymiller** [comment]
I don't have one either, but I know that one at least exists for GABAergic interneurons since it's in the cross species paper: 
![image](https://user-images.githubusercontent.com/25486679/122267936-4ef19600-ce90-11eb-8e81-2d62647fc35b.png)
I'll ask Nik Jorstad about this and post it when I have it.  It is worth noting that the parent child structure in this tree does not perfectly match expectations based on cell type names, as is the case for some examples in the mouse taxonomy.  These inconsistencies are already addressed in the nomenclature table.

**Comment by jeremymiller** [comment]
As discussed in the slack thread, here is the alternative to the dendrograms (tables of parent child relationships) as well as the updated nomenclature tables and updated mouse dendrogram [ontology_files_M1.zip](https://github.com/obophenotype/brain_data_standards_ontologies/files/6689786/ontology_files_M1.zip).  Let me know here or via slack if you have any questions or issues.

**Comment by dosumis** [comment]
@hkir-dev - new format to deal with (parent-child duples). 

@jeremymiller  -

I was assuming that, as with the dendrograms, any node referenced in cell_set_heirarchy_ = a true dendrogram node, corresponding to a cluster of cells and that cross dendrogram groupings would not be in the cell_set_heirarchy, but would be in the nomenclature_table_ with multiple entries in child_cell_set_accessions.  Right now we make data-defined classes for the former, not the latter.

I checked for this in CCN201912131 and found:

cell_set_preferred_alias | cell_set_label | cell_set_accession | cell_set_aligned_alias | cell_set_additional_alias | cell_set_alias_assignee | cell_set_alias_citation | cell_set_structure | cell_set_ontology_tag | taxonomy_id | species | modality | child_cell_set_accessions
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Lamp5 | RNAseq 001-008, 014-015 | CS201912131_128 | Lamp5 |   | Nikolas Jorstad | 10.1101/2020.03.31.016972 | primary motor cortex | UBERON:0001384 | Human | RNAseq | CCN201912131 | CS201912131_1\|CS201912131_2\|CS201912131_3\|CS201912131_4\|CS201912131_5\|CS201912131_6\|CS201912131_7\|CS201912131_8\|CS201912131_14\|CS201912131_15
Sncg | RNAseq 009-013, 016-018 | CS201912131_129 | Sncg |   | Nikolas Jorstad | 10.1101/2020.03.31.016972 | primary motor cortex | UBERON:0001384 | Human | RNAseq | CCN201912131 | CS201912131_9\|CS201912131_10\|CS201912131_11\|CS201912131_12\|CS201912131_13\|CS201912131_16\|CS201912131_17\|CS201912131_18


Parent_accession | Child_accession
-- | --
CS201912131_128 | CS201912131_1
CS201912131_128 | CS201912131_152
CS201912131_128 | CS201912131_153
CS201912131_128 | CS201912131_154
CS201912131_128 | CS201912131_157
CS201912131_129 | CS201912131_11
CS201912131_129 | CS201912131_155
CS201912131_129 | CS201912131_156
CS201912131_129 | CS201912131_158

So seems not to be the case.  Is there any way we can distinguish?

**Comment by dosumis** [comment]
Before, we had dendrogram nodes that correspond to clusters from analysis - all related in a single inheritance taxonomy -  & synthetic nodes that group these.  I would like to be able to distinguish these using the new files.

**Comment by shawntanzk** [comment]
There isn't a cross-species dendrogram. We will base this on the nomenclature file
