### ISSUE TITLE
MY-projecting L5 ET in table is inconsistent with figure in paper

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#107]
The paper has

![image](https://user-images.githubusercontent.com/112839/122261632-80885280-cecc-11eb-9096-7d404391d0c4.png)

Note single node under MY Projecting

But the dendrogram table has two nodes under it:

MY-projecting L5 ET | &nbsp; | RNAseq 070-071 | CS202002013_260 | &nbsp; | MY-projecting L5 ET | Federico Scala | 10.1101/2020.02.03.929158 | primary motor cortex | UBERON:0001384 | CCN202002013 | Mouse | RNAseq | CS202002013_70\|CS202002013_71
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Is one of these wrong/out-of-date?

**Comment by dosumis** [comment]
CC @shawntanzk

**Comment by jeremymiller** [comment]
This is probably an error on my part.  Let me fix this along with the the other L5 ET inconsistencies.

**Comment by dosumis** [comment]
@shawntanzk  - can you check if fixed in latest spreadsheet?

**Comment by shawntanzk** [comment]
@dosumis it is fixed with new spreadsheet, but we dont have 'cell_set_accession' fixed yet (have already requested @jeremymiller to provide) so that fix is not complete - will close this once that is done

**Comment by dosumis** [comment]
https://github.com/obophenotype/brain_data_standards_ontologies/issues/102#issuecomment-881308315

**Comment by shawntanzk** [comment]
fixed with https://github.com/obophenotype/brain_data_standards_ontologies/commit/151b7569c948b51d2a4b092eeace982a70014c48
