### ISSUE TITLE
Mockup for autocomplete searchbox

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#115]
Mockup for autocomplete searchbox for use cases workshop session
@shawntanzk to add that to workshop materials (https://drive.google.com/drive/folders/1KpohBsU8wmUGY_E7p4xCXjjlkv9HcCRg) and write about that in brief (https://docs.google.com/document/d/1nETOTXSNMNnHUubk28_lUQ3bD_e122JKi6kl1LVqi-E/edit)

**Comment by hkir-dev** [comment]
a sample service added: http://ec2-3-143-113-50.us-east-2.compute.amazonaws.com:8484/autocomplete/demo.html
there is an invisible button and text box on top of mock-up image. We can improve demo based on new requests.

**Comment by shawntanzk** [comment]
amazing :) thanks!
