### ISSUE TITLE
Mockup ontology toolbar for workshop

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#116]
https://www.figma.com/file/WhKGRN9tDEa8ScpLeZEHaB/Untitled?node-id=0%3A1

to do: 

- [x] replace badges with actual neo4j results
- [x] confirm what we are allowed to use (perhaps cut to just the side bar?) 
- [x] add mockups to workshop materials https://drive.google.com/drive/folders/1KpohBsU8wmUGY_E7p4xCXjjlkv9HcCRg

related to: #108

**Comment by shawntanzk** [comment]
Modifying cell type card ontology toolbar: 

for cell type cards - side bar

Each cell type card page = a dendrogram node = a cluster of cells & related data.
Each dendrogram node has class for which it is an exemplar.  This is the primary class we display information about in the side bar:
	Label:
	Definition:
	Synonyms (? poss redundancy with cell type card aliases)
	Parent class(es) - can include CL classes - not directly linked to dendrogram nodes
	Expressed genes (markers)
	Tags (= neo labels) - click on these to drive faceted browsing.

**Comment by shawntanzk** [comment]
Currently, badges do not have species and brain region as they aren't labels - they are something I think would be useful later on - shall I add them to the neo4j labels @dosumis?

**Comment by shawntanzk** [comment]
Completed mockup: https://www.figma.com/file/WhKGRN9tDEa8ScpLeZEHaB/Workshop-Mockups?node-id=0%3A1

**Comment by shawntanzk** [comment]
> Currently, badges do not have species and brain region as they aren't labels - they are something I think would be useful later on - shall I add them to the neo4j labels @dosumis?
> 
> I will add this

Done this on https://github.com/obophenotype/bds-pipeline-config/blob/extend-neo4j2owl-config.yaml/config/prod/neo4j2owl-config.yaml @hkir-dev happy for you to update this

**Comment by dosumis** [comment]
Looks good

![image](https://user-images.githubusercontent.com/112839/123236237-8be30b80-d4d4-11eb-9672-6c83bc306722.png)

Maybe change 
RF markers -> markers
& 
properties -> tags
