### ISSUE TITLE
Change Neo4J Labels for Morpho back to 'bearer_of' some 'PATO:XXXX'

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#121]
Currently using BDS_exemplar for morpho types, 
should change it back to 'bearer_of' some 'PATO:XXXX' 

Use this branch: 
https://github.com/obophenotype/bds-pipeline-config/blob/extend-neo4j2owl-config.yaml/config/prod/neo4j2owl-config.yaml

**Comment by shawntanzk** [comment]
Made the edits in https://github.com/obophenotype/bds-pipeline-config/blob/extend-neo4j2owl-config.yaml/config/prod/neo4j2owl-config.yaml 
Have left this open before @hkir-dev pulls it in to whichever branch is needed - happy to move to to closed once done.

**Comment by hkir-dev** [comment]
Merged changes to https://github.com/obophenotype/bds-pipeline-config/blob/dev/config/prod/neo4j2owl-config.yaml
