### ISSUE TITLE
Faceted browsing results table mockup:

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#122]
Faceted browsing results table mockup:

Query: 
MATCH (n:Martinotti:Class)-[:has_exemplar]->(i:Individual) return n.label, i.cell_set_preferred_alias + i.cell_set_additional_aliases, labels(n)

Show example:
From a single tag -> results table mockup
	Header = all tags in table

Columns: 
Ontology term | synonyms  | cell_set_preferred_alias | tags

**Comment by shawntanzk** [comment]
Mockup: https://www.figma.com/file/WhKGRN9tDEa8ScpLeZEHaB/Workshop-Mockups?node-id=0%3A1

**Comment by shawntanzk** [comment]
@dosumis also added this spreadsheet with all the labels to the workshop materials: https://docs.google.com/spreadsheets/d/1JGpZTEMj_f8qVr9krD1km5fs3WAWr5ts7F5C8DcUy_U/edit#gid=0

**Comment by dosumis** [comment]
Spreadsheet looks good.  Please change nodes -> cell though.

Thanks!
