### ISSUE TITLE
Fix autocomplete demo to limit to BDS ontology

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#125]
Currently searches all ontologies on OLS

**Comment by hkir-dev** [comment]
Demo updated in the server: http://ec2-3-143-113-50.us-east-2.compute.amazonaws.com:8484/autocomplete/demo.html

Autocomplete search scope limited to BDS2 ontology. Form generates related scope limiting query parameters: http://ec2-3-143-113-50.us-east-2.compute.amazonaws.com:8080/api/select?q=et&ontology=bds2

Search button (at the left of the search box) linked to the bds2 ontology search page: http://ec2-3-143-113-50.us-east-2.compute.amazonaws.com:8080/search?q=fb&ontology=bds2

**Comment by dosumis** [comment]
Looks good.
