### ISSUE TITLE
Drive autocomplete demo from sub-ontology

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#126]
This is a stretch goal for the workshop.

TODO: make subontology with cells only.  This should be straightforward with ROBOT 
- Spec: subontology should only have subclasses of 'cell' (cell ontology).
- Add this to OLS for us in autocomplete

**Comment by hkir-dev** [comment]
Is this query sufficient to build sub ontology: https://gist.github.com/hkir-dev/17ff24bdcbd74d0d21eae4777e2dcdea

Generated cells subset is : [https://app.zenhub.com/files/299404353/98b4b5a9-3f7a-4795-8ffe-fab3fb9dc9e6/download](https://app.zenhub.com/files/299404353/98b4b5a9-3f7a-4795-8ffe-fab3fb9dc9e6/download)

**Comment by hkir-dev** [comment]
Filtering created a much compact subontology:

```
robot filter --input bdscratch-full.owl --term CL:0000000 --select annotations --select descendants --axioms all --signature true --trim true --output bdscratch-filter.ofn
```

[https://app.zenhub.com/files/299404353/4a45c4fb-74f6-41f7-b816-8da9c638e2db/download](https://app.zenhub.com/files/299404353/4a45c4fb-74f6-41f7-b816-8da9c638e2db/download)

**Comment by dosumis** [comment]
Looks good!  Probably shouldn't be used for browsing, but much better for driving autocomplete than full file.

**Comment by hkir-dev** [comment]
OLS deployment of the subontology completed: http://ec2-3-143-113-50.us-east-2.compute.amazonaws.com:8080/ontologies/bds_cell

Auto complete demo redeployed (**_Warning: you may need to clean browser cache_** via `Ctrl` + `Shift` + `R` the demo page): http://ec2-3-143-113-50.us-east-2.compute.amazonaws.com:8484/autocomplete/demo.html

Old version (with the whole ontology) also still exists: http://ec2-3-143-113-50.us-east-2.compute.amazonaws.com:8484/autocomplete/demo_bds.html
