### ISSUE TITLE
Mock up search results for ontology term search

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#127]
The point of the ontology driven search is to find cell type cards, not to find ontology terms.

Proposed behaviour of lexical search results:

If the hit is an ontology term corresponding to a cell type card, then that card is returned

If the hit is an ontology term for a class that groups cell type cards, then a results page of all subsumed cell type cards should be returned - with ontology term details in the side bar (as for cell type card pages).  results return should be identical to faceted search.

The aim of this ticket is to mock up a search results page for an ontology term.

Query to use for mockup

```cql
MATCH (c:Class)<-[:SUBCLASSOF]-(bds_class:Class)-[:has_exemplar]->(i:Individual)
WHERE label = '<some label in here>'
RETURN bds_class.label, i.cell_set_preferred_alias,
 i.cell_set_additional_aliases, labels(bds_class)
``` 
(@shawntanzk  - return might not be quite right for what you're doing for faceted search - likely needs synonyms. Please update.)

**Comment by dosumis** [comment]
Stretch goal.

**Comment by shawntanzk** [comment]
Is this what you mean @dosumis 

```
MATCH (c:Class)<-[:SUBCLASSOF]-(bds_class:Class)-[:has_exemplar]->(i:Individual)
WHERE c.label = 'L5 ET primary motor cortex glutamatergic neuron (Mus musculus)'
RETURN bds_class.label, i.has_exact_synonym, i.cell_set_preferred_alias, i.cell_set_additional_aliases, labels(bds_class)
```

![Screenshot 2021-06-24 at 11 43 39](https://user-images.githubusercontent.com/76212760/123249944-6d374180-d4e1-11eb-851a-7e77d3cd38cc.png)

**Comment by shawntanzk** [comment]
see mockup: https://www.figma.com/file/WhKGRN9tDEa8ScpLeZEHaB/Workshop-Mockups?node-id=0%3A1

**Comment by dosumis** [comment]
Just realised that L5 ET is not a great example as it has a cell type card.  Sorry!

A MET type that cuts across the taxonomy would be better.   Any ideas?

**Comment by shawntanzk** [comment]
Just look through, those that cut the taxonomy, like Large CCK basket cell, have not been added to CL/our ontology. 
Noticed that L5 T Martinotti is problematic too - need to double check this, will make a ticket. 
Happy to do any MET type, perhaps non-MY projecting keeping with the cell type cards? It doesnt cut across the taxonomy but has the same idea?

**Comment by shawntanzk** [comment]
Added non-medulla ET (easy to mock up since everything was there anyway) - think we can show all 3 as examples (searching for leaf node, searching for parent class, searching for MET type)

**Comment by shawntanzk** [comment]
oh wait take it back, if search for parent type that happens to be a cell type card, the cell type card would show up - maybe we dont show that one

**Comment by shawntanzk** [comment]
> It is in CL though - so kinda counts. But perhaps better to have an example that groups more.

can do a big grouping like PVALB?

**Comment by dosumis** [comment]
Pvalb could be good.  Or perhaps just do Martinotti?

**Comment by dosumis** [comment]
Looks nicely cross-cutting with some gaps
![image](https://user-images.githubusercontent.com/112839/123282661-a16f2a00-d502-11eb-90e2-0247d92bf23d.png)

Easy to present along with dendrogram to tell a clear story

**Comment by dosumis** [comment]
Although might look redundant with tags.

**Comment by shawntanzk** [comment]
worry with L5 T martinotti: https://github.com/obophenotype/brain_data_standards_ontologies/issues/129
