### ISSUE TITLE
Improve standards for specifying grouping nodes

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#13]
When overlaying classifications on those specified by dendrograms, we sometimes need to specify new grouping nodes.  This is currently done as follows:

cell_set_preferred_alias | cell_set_label | cell_set_ accession | cell_set_ aligned_alias | cell_set_ additional_alias | cell_set_ alias_assignee | cell_set_ alias_citation
-- | -- | -- | -- | -- | -- | --
Large CCK basket cell | RNAseq 009-012 | CS202002013_256 | None | Large CCK basket   cell | Federico Scala | 10.1101/2020.02.03.929158

This means we mean we need a new node that groups existing nodes 009-012 and that this corresponds to a large CCK basket cell, according to the reference provided.

But parsing the string `RNAseq 009-012` is not a reliable way of doing this, especially as this cell_set_label naming scheme is not universally applied.  It would be much better if we had a column that listed sub-nodes, separated by pipes

e.g., in this case we would have: CS202002013_9|CS202002013_10|CS202002013_11|CS202002013_12

**Comment by jeremymiller** [comment]
We can do exactly this.  I will update [the CCN repo](https://github.com/AllenInstitute/nomenclature) to include child_cell_set_accessions by default in the output.

**Comment by dosumis** [comment]
Representation in tsv files is now fixed, but we need  some work on schema & code for utilising these.  Will make new ticket.
