### ISSUE TITLE
Cross species mockup

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#130]
Need a mockup for workshop to show how cross species linkages might work in the ontology, this should integrate discussions with @jeremymiller. 

Plan: 

- [x] Workshop 1 (review of ontology) - provide an example of this link 
- [x] Workshop 2 (use cases) - add a cross species parent term in the ontology side bar to see how it links

**Comment by shawntanzk** [comment]
I've mocked up an example here: https://docs.google.com/document/d/1f3O-kMXc7JYgBrtRwmktnnIVtBHXxEzE3YmoJRbmy-A/edit 
would like review on it @dosumis

**Comment by jeremymiller** [comment]
This looks good to me.  The only think I'm not sure about it the parent classes for "L5 IT_2 primary motor cortex glutamatergic neuron (Mammalia)".  It seems weird that there would be a higher-resolution parent in the mammalian ontology (L5 IT_2) than in the mouse ontology (L5 IT).  That said, I understand why this is the case and don't have a better way to do it, so maybe worth some discussion at the workshop!
