### ISSUE TITLE
Write functional spec for improved synonym handling for templated terms

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#140]
* cell set pref alias - if taken as-is are broad synonyms, but they can be made exact by adding brain region and species scope on to the end of the name.
* Decide whether we want to keep names like n17 or RNAseq10-15 on classes, or should these only be on individuals? related: do CS202002013_1 type of names need to be synonyms if they are already exemplar_of? 
* Decide whether/how to do abbreviation expansion on synonyms. (eg L5 ET -> Layer 5 Extratelencephalic-projecting; this will also allow search with the word "layer") 
* TBD - do we need to put those gene names synonyms in (especially since they are really long) -> need to axiomatize genes

**Comment by shawntanzk** [comment]
> Decide whether we want to keep names like n17 or RNAseq10-15 on classes, or should these only be on individuals? 

Given that one of the use cases is accessing the underlying data, I think it would be useful the keep the RNAseq synonym - when I was handling the cross-species example, RNAseq name was the only way to navigate those tables at times. I think we just need to have something in the name that shows which dataset it's from (and of course a reference link out and all).

**Comment by dosumis** [comment]
Take all cell_set_additional_alias; cell_set_preferred_alias etc (but not cell_set_label) -> exact_synonym via mega pattern - with all extended to reflect scope, as for synonym (adding abbv for region and species).  exact_synonyms should be removed from the robot template.

**Comment by shawntanzk** [comment]
Postpone until DOSDP tools updated

**Comment by shawntanzk** [comment]
This should be done, if not, please open new tickets on individual issues that need to be addressed
