### ISSUE TITLE
curate non-leaf nodes allen markers

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#143]
non-leaf nodes do not have their allen markers curated, hence it is not showing up in defs. 
eg L5/6 CCK cell needs CCK curated on it

**Comment by shawntanzk** [comment]
Issue was that the names were in cell_set_additional_alias -> have now curated CCK onto Allen_markers.tsv
@hkir-dev I've left it on a new branch that I took from the workshop branch, not sure if I should merge there, but heres the commit, happy for you to merge wherever you need etc.: https://github.com/obophenotype/brain_data_standards_ontologies/commit/e440cf707c4506fa67ed546f72c3150c38fdb0c3 

@dosumis I could only find CCK that fits this well - the others are cross species which I can't curate those markers on as I'm unsure even given their names - example being: 
CS202002013_2  (Lamp5 Elgn3_1) has cell set additional alias Sncg_4 & Alpha7 cell, and importantly, does not express sncg
I'm happy to go through each of them to check etc, but I think we need a solution to the problem Jeremy pointed out before we do anything with these nodes.

**Comment by dosumis** [comment]
Need more detail to understand this.  Is the current problem not just for mouse and so multi-species not an issue?

**Comment by shawntanzk** [comment]
oh actually I can go make sure all the child nodes have the markers and curate it on since this is specific to mouse - will do. Sorry, my mind keeps thinking this node is shared between species for some reason when it's not.

**Comment by shawntanzk** [comment]
@hkir-dev done, see https://github.com/obophenotype/brain_data_standards_ontologies/blob/add-CCK-curation-to-allen-markers/src/markers/CS202002013_Allen_markers.tsv

@dosumis I've curated the markers which child nodes fit and have markers in cell_set_additional_alias

**Comment by hkir-dev** [comment]
Pull request to workshop branch created https://github.com/obophenotype/brain_data_standards_ontologies/pull/144
When a new official dosdp & odk version released that supports our new pattern format (multi_clause), we can pull all updates to master.
