### ISSUE TITLE
DOSDP tools - support 0-many var input

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#147]
Dummy ticket for ZenHub tracking of https://github.com/INCATools/dosdp-tools/issues/334

Background - this is needed to switching to a unified DOSDP template that can take a list of markers and turn this into a list of axioms.

**Comment by hkir-dev** [comment]
Dosdp development completed: https://github.com/INCATools/dosdp-tools/pull/349
New patterns added: https://github.com/obophenotype/brain_data_standards_ontologies/tree/dosdp_based_pipeline/src/patterns/dosdp-patterns
