### ISSUE TITLE
Update taxonomy.csv files to latest

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#148]
For now - these should be extracted from the latest spreadsheet shared by @jeremymiller and placed in src/dendrograms following the naming convention used for the mouse taxonomy.

@jeremymiller:  Any changes in the mouse table should be reflected in an updated dendrogram JSON file.

**Comment by shawntanzk** [comment]
@jeremymiller currently we have a tab called 'child_cell_set_accessions' in https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/dendrograms/nomenclature_table_CCN202002013.csv that has the 'cell_set_accession' of all the child nodes - was wondering if you could provide something like that? current spreadsheet you have passed to us only has cell_set_label (RNAseq XXX) to label which are the child nodes. @dosumis just to check, we did get that file and it is not generated by us by reading off the excel sheet right? 

Also, I've just noticed these nodes missing and are now in cell_set_additional_alias. 
MY-projecting L5 ET		RNAseq 070-071	CS202002013_260
Non-MY-projecting L5 ET		RNAseq 072-073	CS202002013_261
It is correctly represented now in terms of the RNAseq child nodes (I rmbr requesting that change), but just want to double check that this is correct that the two accession should be deleted.

**Comment by shawntanzk** [comment]
I've placed the new spreadsheet into a new branch:  https://github.com/obophenotype/brain_data_standards_ontologies/blob/16Jun21-Dendrogram-Update/src/dendrograms/cell_set_nomenclature.xlsx

**Comment by dosumis** [comment]
Thanks.  Please split the cell_set_nomenclature sheet into individual csvs files following this naming scheme:

 nomenclature_table_CCN202002013.csv

Thanks!

**Comment by shawntanzk** [comment]
@dosumis I assume you mean for the other taxonomies?

**Comment by dosumis** [comment]
For all - presumably `nomenclature_table_CCN202002013.csv` has changed

**Comment by shawntanzk** [comment]
Commit for all other taxonomies here: 
https://github.com/obophenotype/brain_data_standards_ontologies/commit/3b4bd3602853a9ae676e584be60baf3960c684ea 
Currently still missing child_cell_set_accessions - will update once I get them

**Comment by shawntanzk** [comment]
fixed with https://github.com/obophenotype/brain_data_standards_ontologies/commit/151b7569c948b51d2a4b092eeace982a70014c48
