### ISSUE TITLE
Dump termInfo JSON to SOLR

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#149]

**Comment by hkir-dev** [comment]
First version of the dump generated: https://github.com/obophenotype/brain_data_standards_queries/blob/main/dumps/individuals_metadata_solr.json
Also indexed to the solr: http://ec2-3-143-113-50.us-east-2.compute.amazonaws.com:8993/solr/#/bdsdump/query
Can be queried by [id](http://ec2-3-143-113-50.us-east-2.compute.amazonaws.com:8993/solr/bdsdump/query?q=id:%22http://www.sem[…]tandards/AllenDendClass_CS202002013_182%22) and [label](http://ec2-3-143-113-50.us-east-2.compute.amazonaws.com:8993/solr/bdsdump/query?q=label:*L5%20IT*).
