### ISSUE TITLE
Review .json files

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#153]
Check structures etc. for new json files for human and marmoset
https://github.com/obophenotype/brain_data_standards_ontologies/tree/16Jun21-Dendrogram-Update/src/dendrograms

**Comment by shawntanzk** [comment]
@dosumis do you know where I can get a high quality version of this: 
![image](https://user-images.githubusercontent.com/76212760/128771973-fbfdcbc1-cc90-4293-b2e1-7dd0cf9fead1.png)
Checking it against the json file - looks alright so far, but its hard to see with the version I have/the one I can get from the preprint.

**Comment by dosumis** [comment]
@jeremymiller - can you provide a higher quality image of the figure?

**Comment by jeremymiller** [comment]
It is Figure one from this paper: https://www.biorxiv.org/content/10.1101/2020.03.31.016972v2.full.  If that version isn't good enough quality, ask Trygve or Nik.

**Comment by shawntanzk** [comment]
Move to use tsv files instead
