### ISSUE TITLE
Meis2 Cluster

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#154]
It turns out there are two nodes called Meis2, a cluster and a node (which includes the Meis2 cluster and one other).  Jeremy has changed the cluster "Meis2 (cluster)" to disambiguate

In terms of mapping, my suggestion (which Jeremy agrees with) is that Meis2 is mapped to the the one that will be called Meis2 (instead of the cluster one). 

*note: Meis2 node includes Meis2 (cluster) and Meis2 Top2a

I am not sure that this is the case now, but with the updated files, I will check this.

**Comment by shawntanzk** [comment]
see https://github.com/obophenotype/brain_data_standards_ontologies/commit/545cc01c90e371d13959b309e301f1536f4a0cf9

**Comment by shawntanzk** [comment]
Mapping as root node in taxonomy_details.yaml is correct

**Comment by shawntanzk** [comment]
@dosumis just wanted to make sure you see this implementation before I close this issue

**Comment by dosumis** [comment]
Confused by terminology:  Meis2 cluster = leaf node?  & Meis2 = grouping node for Meis2 (cluster) and Meis2 Top2a ?

Meis2 = root node for type.  This is GABAergic, but not closely related to other GABAergic neurons.  Is this correct?

**Comment by shawntanzk** [comment]
> Confused by terminology: Meis2 cluster = leaf node? & Meis2 = grouping node for Meis2 (cluster) and Meis2 Top2a ?

yes this is correct, and according to Jeremy, the more accurate way to map Meis2 is to the grouping node

> Meis2 = root node for type. This is GABAergic, but not closely related to other GABAergic neurons. Is this correct?

That is correct, as other taxonomies might not have GABAergic as the parent term for Meis2, we've done Meis2 as a root node and mapped the CL term to the grouping node

**Comment by dosumis** [comment]
So mouse maps to 'Meis2 GABAergic cortical interneuron', but other species Meis2 nodes don't - at least for now.  Is there a Meis2 node in the cross-species dendrogram?

**Comment by shawntanzk** [comment]
> So mouse maps to 'Meis2 GABAergic cortical interneuron', but other species Meis2 nodes don't - at least for now. Is there a Meis2 node in the cross-species dendrogram?

I need to do research for the rest - it is on an issue at the moment that I will get to. 
Just checked with cross-species dataset (CS202002270), there isn't Meis2 on it
