### ISSUE TITLE
CL and Pref Label having the same name

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#156]
Currently pref labels might have the same/similar name as CL terms making it confusing
A previous example was L5 T Martinotti cell (see #129) 
Another example of this that is more blatant is neurogliaform cell in which there is a CL term that correctly encompasses L5,6 neurogliaform too, but also a BDSO term that only encompasses neurogliaform lamp5 (which to be fair is a bit confusing a name too). My guess is that is has to do with some transcriptomic grouping thing? am I right @jeremymiller?  
![Screenshot 2021-08-12 at 13.24.51.png](https://images.zenhubusercontent.com/60ae6c7d916945778aa3f3c2/b811a279-4742-4529-a0c3-2a2650b10266)
Either way, we should find a way to clarify these naming schemes in the BDSO terms by changing pref label to something else

**Comment by jeremymiller** [comment]
I'm not sure I'm following, but it seems to me that "L5,6 Neurogliaform Lamp5..." should be a child of "Neurogliaform Lamp5 ...," and that the extra "Neurogliaform cell" node under that should be removed (e.g., there shouldn't be any cell type that has the same parent and child).  Is this what you are asking?

**Comment by shawntanzk** [comment]
![Screenshot 2021-08-12 at 17 06 37](https://user-images.githubusercontent.com/76212760/129230293-6a54e5c8-5ebc-4b15-841a-1c93bca283fa.png)
I think this is the issue - there's a MET term for neurogliaform cell and one for L5,6 NGC cell (which i take NGC as neurogliaform cause lamp5 lhx6 is a https://www.biorxiv.org/content/10.1101/490797v1.full.pdf which does bring up more issues, but we are taking the data at face value atm) 
I guess now that you mentioned, it looks more like an assigning problem than a transcriptomics problem. 
Wonder if NGC cell could actually mean neurogliaform chandelier cell now that I'm re-looking at it?

**Comment by shawntanzk** [comment]
> Wonder if NGC cell could actually mean neurogliaform chandelier cell now that I'm re-looking at it?

From https://www.biorxiv.org/content/10.1101/490797v1.full.pdf 

 In particular, the Nkx2.1 and Lhx6
transcription cascade drives the MGE but not the CGE clade (23, 26, 27). Interestingly and
surprisingly, a group of Lamp5 subclass interneurons with prominent Lhx6 and Nkx2.1 expression was
classified as CGE derived putative neurogliaform cells (NGFC) (16). Notably, this Lamp5-Lhx6 type
was identified as transcriptionally similar to the CHC2 type, which was considered L5/6 chandelier
cells that were fate mapped from Nkx2.1 progenitors in the MGE clade (20).

**Comment by jeremymiller** [comment]
NGC means Neurogliaform Cell.  Chandelier cells are completely different.

**Comment by shawntanzk** [comment]
> NGC means Neurogliaform Cell. Chandelier cells are completely different.

Yeah, in that case the reason for the above is that MET type neurogliaform cell doesnt encompass L5/6 NGC whereas CL pulled neurogliaform (by function of both neurogliaform and L5/6 NGC having "has characteristic" some "neurogliaform morphology") encompasses both those types. 

We either have to rename it or remove it. I also think this is a problem in CL actually, cause technically neurogliaform lamp5 should include L5/6 neurogliaform.

**Comment by shawntanzk** [comment]
Suggestions by @tgbugs 
- When clashes like that happen, can use a tag at end of name eg (BDS Taxonomy) to differentiate and add a comment or something to state that it is defined through the dataset with a xref link out
- Alternatively, for NGC - could it be changed to non L5/6 NGC instead? (not sure how accurate this is @jeremymiller)

**Comment by jeremymiller** [comment]
I'm not sure whether "non L5/6 NGC" would be appropriate in that specific case, although it *probably* is.  My understanding is that most NGCs are in L1, so unless something else is specified (like "L5/6 NGC") that would be my guess about it.  That said, don't update it based on my guess.  Someone should look into the details to confirm.  Maybe Ray could do this?

**Comment by shawntanzk** [comment]
@jeremymiller I think the best way to deal with this issue might be to just remove the label of neurogliaform cell, and allow the reasoner to automatically classify cells with neurogliaform morphology to the CL mapping, this is especially so as there isn't going to be a cell type card for this anyway. Thoughts?

**Comment by jeremymiller** [comment]
That's probably fine.  Make the edits in the appropriate places :-)

**Comment by shawntanzk** [comment]
Fixed in local repo - will make edit in Allen repo and create PR - closing for now to clean up ticket list
