### ISSUE TITLE
Formalising layer information

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#167]
We should add layer information with uberon, however this needs a few things: 
1) Currently, uberon only has layer 1, 5, 6 -> we need to add the rest 
2) not sure how we handle things like layer 2/3 (which is usually lower layer 2 upper layer 3) -> do we but has soma location in both layer 2 and 3?

**Comment by patrick-lloyd-ray** [comment]
Probably wouldn't be "both" but rather "or" (or some intersection, depending on how the layers are defined).

**Comment by shawntanzk** [comment]
Blocks

- [ ] UBERON release for mixed cortical layers (current uberon release cannot be built due to memory issue, need to wait for this to be fixed)
- [ ] Layer information need to be added to CL as equiv terms where possible (https://github.com/obophenotype/cell-ontology/pull/1270) 
- [ ] Curate uberon terms into BDSO

**Comment by shawntanzk** [comment]
Curated uberon terms into BDSO here https://github.com/obophenotype/brain_data_standards_ontologies/commit/e83fbf954d610eeb823fd686743861a2e5355845

**Comment by shawntanzk** [comment]
To do:
- [ ] CL release (pending uberon release - unrelated issue) 
- [ ] refresh imports in BDSO
