### ISSUE TITLE
Using csv files instead of json

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#171]
Human and Marmoset taxonomies cannot be built from json file as nodes are not very useful, and preflabels will be problematic on them. Instead they should be built from the csv files, using the column 'child_cell_set_accessions' for hierarchy. 
https://github.com/obophenotype/brain_data_standards_ontologies/blob/single_dosdp_template/src/dendrograms/nomenclature_table_CCN201912131.csv
https://github.com/obophenotype/brain_data_standards_ontologies/blob/single_dosdp_template/src/dendrograms/nomenclature_table_CCN201912132.csv

Discussion to be had - what becomes an owl class? The column 'cell_type_card' shows if the node will become a cell type card, but, there are a couple of things that might not have cell type cards but we want in the ontology eg:
1) grouping terms like MGE or IT-projecting 
2) Cross species terms like VIP_1 or Lamp5_2 etc. 

TO DO: 

- [ ] Implement using csv to build taxonomy (@hkir-dev)
- [ ] Figure out which terms (or all) gets added into it (add to meeting agenda)
- [ ] Curate CL terms to it (@shawntanzk)

**Comment by hkir-dev** [comment]
Nomenclature table based implementation (only for human) is as follows:
- Class templates: https://github.com/obophenotype/brain_data_standards_ontologies/tree/new_species/src/patterns/data/default
- Individuals template: https://github.com/obophenotype/brain_data_standards_ontologies/blob/new_species/src/templates/CCN201912131.tsv
- Ontology build (without manual curation just for evaluation): https://github.com/obophenotype/brain_data_standards_ontologies/blob/new_species/bdscratch-full.owl

**Comment by shawntanzk** [comment]
Implementation looks alright, and heirachy will be alright have curation (I've checked the OWL individuals and it looks alright, currently I think there are some missing OWL classes, but I think that will be filled through CL curation of the grouping terms), but there are still issues with csv file, which means we still need discussion. 
I've added this to agenda for meeting.

**Comment by hkir-dev** [comment]
CSV based taxonomy will be improved by this issue https://github.com/obophenotype/brain_data_standards_ontologies/issues/174

**Comment by shawntanzk** [comment]
Implementation can be found in: https://github.com/obophenotype/brain_data_standards_ontologies/blob/cross_species/bdscratch-full.owl
