### ISSUE TITLE
Switching to PCL IRIs

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#172]
We should switch IRIs, which are currently based on BDS IDs, to one that follows OBO patterns.
To do this, we will use PCL IDs -> PCL_XXXXXXX
@hkir-dev to look at what is needed to be done for this. 
BDS ID will then be moved to skos:prefLabel
Current prefLabels can be removed as they are already synonyms

**Comment by hkir-dev** [comment]
We need a PCL ID range and a stable IRI mapping approach.

Stable IRI mapping example for range 0010000 - 0018500:
0010000 - 0010100  : helper entities (Cluster, taxonomy, has_age, has_sex, ...)
0010100 - 0010400  : mouse classes (CS201912132_72 -> PCL_0010172)
0010400 - 0010700  : human classes (CS201912131_104 -> PCL_0010504)
0010700 - 0011000  : marmoset classes (CS201912132_72 -> PCL_0010772)
0011000 - 0012500  : other species (up to 10) classes, based on taxonomy.yaml order

0012500 - 0012900  : mouse indvs
0013300 - 0013700  : human indvs
0014100 - 0014500  : marmoset indvs
0014500 - 0018500  : other species (up to 10) indvs

**Comment by shawntanzk** [comment]
Plan:
propose deprecate all current terms in pCL and Shawn will add ‘term replaced by’ & comments to map to our terms

**Comment by shawntanzk** [comment]
Switched
