### ISSUE TITLE
Lacking Oligo in class_curation file

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#176]
Currently some terms (oligo in specific) are missing due to lack of root nodes for them (they used to live in non-taxonomy roots due to not having nodes in json file). Now that we switch to nomenclature file for human and marmoset, we no longer use non-taxonomy roots, and therefore these roots got removed. I have now added them back as taxonomy roots since they would have nodes in nomenclature file - needs refreshing to get them in the curation table. 

https://github.com/obophenotype/brain_data_standards_ontologies/commit/59612140508bf7e3455feb260d1dd1d5841bbc25

I have already curated a whole bunch of stuff, so would need the refresh to keep those curations on it.

**Comment by shawntanzk** [comment]
Note not just oligo are missing - things like pericyte in marmoset is also missing (not sure if adding non-neuronal node as root would solve this)

**Comment by hkir-dev** [comment]
In Marmoset configuration a human node reference is made: https://github.com/obophenotype/brain_data_standards_ontologies/blob/391f8d0c7e4f2466855c29b28c6465e3bfc69f25/src/dendrograms/taxonomy_details.yaml#L243
Should we delete it?

**Comment by hkir-dev** [comment]
Curation tables and the ontology updated in the `cross_species` branch

**Comment by shawntanzk** [comment]
There are still some missing nodes I think - writing this as a note to self, will find what they are and figure out which roots are still missing. @shawntanzk

**Comment by shawntanzk** [comment]
Human taxonomy - all solved

**Comment by shawntanzk** [comment]
Human Taxonomy fixed
@jeremymiller Oligo L3-6 OPALIN LRP4-AS1 exists in the fireplot but not in the nomenclature file - hope it is safe to ignore?

**Comment by shawntanzk** [comment]
Marmoset Taxonomy 
Pericytes still missing - need to add curation for CS201912132_108 (pericyte) to roots

**Comment by shawntanzk** [comment]
> Marmoset Taxonomy Pericytes still missing - need to add curation for CS201912132_108 (pericyte) to roots

issue caused by error in curation, now fixed in https://github.com/obophenotype/brain_data_standards_ontologies/commit/07f89c9f64a2187d684903d7a032a42271bdc922

**Comment by jeremymiller** [comment]
I THINK the oligo issue is that this cell type is in the middle on the neuron part of the tree, which may mess up some of the curation.  If that is not the issue, let me know and I'll look more carefully.

**Comment by shawntanzk** [comment]
@jeremymiller it is not so much that it is the middle of part of the tree, but rather it does not exist in the nomenclature file (https://github.com/obophenotype/brain_data_standards_ontologies/blob/cross_species/src/dendrograms/nomenclature_table_CCN201912131.csv) so it does not exist in the ontology at all

**Comment by jeremymiller** [comment]
Is it possible that it is a name change from this one: Oligo L3-6 OPALIN ENPP6. Or is that one also in the heatmap?  (These version issues will be fixed for any public version of the data / visualizations, etc.)

**Comment by shawntanzk** [comment]
Oligo L3-6 OPALIN ENPP6 is also in the heatmap. I mean for now my bigger concern is if there is any issue in the nomenclature file. But if the nomenclature file is definitely correct, and the fireplots might have error, that's not a huge issue for our side at the moment.

**Comment by jeremymiller** [comment]
Okay then this MIGHT be the outlier cluster that has since been removed (and therefore is not in the taxonomy table).  This is worth confirming with Trygve and/or Nik.  It sounds like the plan is to include Trygve in an upcoming ontology meeting, so maybe we can ask him them.  You should assume that the nomenclature table is correct if there are any inconsistencies.
