### ISSUE TITLE
Creating GCI or union way of mapping gene IDs to PR for CL purposes

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#180]
Currently CL uses PRo for markers (eg expresses some lamp5) 
As we change to Ensembl/NCBIgene we need a way to link these to CL terms (eg Lamp5 GABAergic interneuron) 
@dosumis suggested either a GCI or Union.
I don't fully understand this but it needs implementation (will discuss this and spec this out next meeting).

**Comment by dosumis** [comment]
GCI:  expresses some pro:fu EquivalentTo expresses some ensembl:fu

**Comment by dosumis** [comment]
Union approach is to make a single union class covering gene, protein, transcript etc.  The problem then is what ID to use.

**Comment by dosumis** [comment]
I prefer the GCI approach as it doesn't require minting new IDs or overloading existing ones.   I'd like to use a templating approach.  I _think_ this can be achieved using a DOSDP, but we need to check whether it works.
