### ISSUE TITLE
Switching to use Allen Institute Repo files

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#181]
As Allen institute now places their files in their github repo, we should be using those instead of our internal files - that way if things change, ours keep up to date.
We can do this either by:
1) Linking our pipeline directly to consume their files, or
2) Using an import (running an import line or something to update our files to theirs)

My preference is 2 and we do this through pull requests so we can see what differences there are, but I'm not sure if there's a way to build our pipeline so that there is an easy way to run a single command line to do this? Also not sure what the best conventions are for data management. Need input on this @dosumis @hkir-dev

**Comment by hkir-dev** [comment]
Allen Institute Repo files moved to a [separate folder](https://github.com/obophenotype/brain_data_standards_ontologies/tree/pcl_migration/src/dendrograms/MOp_taxonomies_ontology) to make this operation easier.

Option 2 seems better suited to our pipeline. But current issue is Allen repo is a private repo, either we need an authorized bdso_builder github account or make that repo public.

**Comment by shawntanzk** [comment]
@hkir-dev Allen Repo should be public now - low priority to swap this over, but just letting you know :)

**Comment by shawntanzk** [comment]
Fixed
