### ISSUE TITLE
Move mouse taxonomy to using nomenclature file

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#188]
Due to current issues with mouse taxonomies representation, we have decided to move mouse taxonomy to use nomenclature file like the others.

**Comment by hkir-dev** [comment]
Multi-inheritance support added to fix the first issue. 
Can we check the new ontology: https://github.com/obophenotype/brain_data_standards_ontologies/blob/cross_species/bdscratch-full.owl
And the new visualisation: https://github.com/obophenotype/brain_data_standards_ontologies/blob/cross_species/src/test/test_data/CCN202002013_nomenclature.png
