### ISSUE TITLE
Develop naming scheme for data-driven classes

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#19]
Data driven classes need unique names and synonyms.  They can keep non-unique shorter context specific names where there are clear use-cases for these.

Rough draft
1. Node only automatically gets a name if it has a preferred alias that is not some simple derived thing (e.g. RNAseq 058-085)
2. Include some name transformation rules that transform some names taking into account major branches
3. append: 'of {brain region} {{species})'

We need a similar system for symbols - keeping short names, but with context.

e.g. 

L2/3 IT -> 
label: L2/3 intratelencephalic projecting glutamatergic neuron of primary motor cortex (Mus musculus)
symbol: L2/3 IT MOP (Mus)

**Comment by patrick-lloyd-ray** [comment]
This is a great idea. AIBS has a nomenclature standard for data sets, so maybe there is a way to coordinate at some level if these are interacting. 

BTW, I think 'IT' in the example is "intratelencephalic-projecting" -- this demonstrates the need for this schema.

**Comment by dosumis** [comment]
Add symbols to BDS classes - recipe:

stem = 'preferred_cell_set_alias' or 'additional_cell_set_alias'[0] if  'preferred_cell_set_alias'  is null
symbol = stem + ' ' + brain_region_abbv + ' ' + species_abbv

brain_region_abbv & species_abbv will be recorded in  taxonomy_details.yaml for each taxonomy.
this will be used to populate  columns in dosdp_tsv driving a symbol recipe in the DOSDP.

- [ ] Extend schema for  taxonomy_details.yaml to add new keys @dosumis 
- [ ] Extend dosdp mega template to add symbol recipe @dosumis 
- [ ] Write pipeline code to populate dosdp tsv. @hkir-dev 
- [ ] Add abbreviations to YAML @shawntanzk

**Comment by dosumis** [comment]
First 2 steps done.  Passing off to @hkir-dev for next step.

**Comment by hkir-dev** [comment]
Third step is done.

@shawntanzk can you update added dummy abbreviations:

https://github.com/obophenotype/brain_data_standards_ontologies/blob/d36de2cfa35dd8f0024188187e3d61a65485c2d8/src/dendrograms/taxonomy_details.yaml#L10
https://github.com/obophenotype/brain_data_standards_ontologies/blob/d36de2cfa35dd8f0024188187e3d61a65485c2d8/src/dendrograms/taxonomy_details.yaml#L14

**Comment by shawntanzk** [comment]
@hkir-dev couldnt write on that branch so i created one off it - https://github.com/obophenotype/brain_data_standards_ontologies/blob/abbv/src/dendrograms/taxonomy_details.yaml 
happy for you to merge to whichever is the correct branch. 
Thanks :)

**Comment by hkir-dev** [comment]
Updated in the banch

**Comment by shawntanzk** [comment]
Wonder how we would handle other abbreviations (eg projections such as IT, ET) @dosumis

**Comment by dosumis** [comment]
> Wonder how we would handle other abbreviations (eg projections such as IT, ET) @dosumis

We keep them as-is.  The aim here is to have something close to the symbols defined by the Allen/BICCN but to extend to include scope.  We should also consider adding symbols in CL for grouping class names from the nomenclature.

**Comment by hkir-dev** [comment]
Implementation completed and merged: https://github.com/obophenotype/brain_data_standards_ontologies/pull/131
