### ISSUE TITLE
Define standard JSON-LD structure for representing sc transcriptomic clusters and provide R bindings

### ISSUE THREAD

**Issue by cmungall** [obophenotype/brain_data_standards_ontologies#2]
The objective here is to have a standard RDF/OWL representation of cell clusters such that the reasoning strategies in #1 will work. It will be easier for people to provide this to us if we have people provide JSON/JSON-LD.

```
[
 {id: CLUSTER_ID,
  subcluster_of: PARENT_CLUSTER_ID,
  <any other metadata>
 },
```

If we can provide a simple R/python library for generating these it may be easier to integrate with existing scSeq workflows

@dosumis - does this make sense?

In the proposal we mention https://loompy.org/ but not totally clear how that fits in

**Comment by dosumis** [comment]
> does this make sense?

I think so.

> In the proposal we mention https://loompy.org/ but not totally clear how that fits in

Probably doesn't fit with this aim.  But might be downstream of it. Our collaborators at ScOPE have a modified loompy format that can save clusterings + ontology annotations along with the expression matrix they refer to.  Clustering info lives in JSON in the loom file header.  However, I don't believe it does hierarchical clustering, which is what we need.  OTOH - the same approach of storing annotations in JSON in the header could be used to share hierarchical clusterings with data - once we have a standard.

**Comment by dosumis** [comment]
CC @jeremymiller what representations do you currently use?

**Comment by cmungall** [comment]
@jeremymiller provided a sample file in slack, I added to a scratch folder, thanks:

https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/scratch/dend.json

**Comment by dosumis** [comment]
Did some hacking on the JSON here:  https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/scratch/allen_taxonomy_hack.ipynb

**Comment by dosumis** [comment]
Closing as superceded by pipeline work.
