### ISSUE TITLE
CL terms Granularity

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#202]
Currently terms added for BDS in CL are too granular -> this is esp so given we can’t really map any terms for human and marmoset to BDSO given how messy the hierarchy is. 

Wait until we move over to PCL names - that way the ones that we want out of CL can move to PCL if we still want them in BDSO

Shawn to draft out idea on what should stay in CL what move to PCL

**Comment by dosumis** [comment]
1. Remove all non-mouse terms.
2. Make mouse terms -> species general.

**Comment by shawntanzk** [comment]
certain terms might make more sense atm as species specific as they only have data from mouse (though I would need to do more research into each of them to see how generalizable they are to other species) - Examples of these are the GABAergic MET terms - will continue working on these to find a good solution

**Comment by shawntanzk** [comment]
The rest of the terms left unmerged - I do not think we can justify making them species agnostic. Perhaps they might live in PCL once we migrate. For now, I think what is in the PR is all we can do. Left it as draft as would like to wait for discussion on it.
