### ISSUE TITLE
Create columns to override definitions

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#207]
As cross-species terms and non-taxonomy nodes do not have NS forest, they currently do not have any definitions.
To solve this, we need to add definitions that are linked to data.
In DOSDP-tools can add a definition column that will overwrite automated definition processes. 
To do:
- [x] @hkir-dev to create the columns for definitions
- [x] @shawntanzk to write up definitions that link directly to data 
- [ ] @dosumis to workshop these definitions 
- [ ] @shawntanzk to add these definitions manually to the columns in point 1

**Comment by shawntanzk** [comment]
Workshopping definition: 

A [gross cell type] of the [species] [brain region]. These cells represent the transcriptomically defined cluster [cluster ID] in the dataset from the referenced publication and are transcriptomically homologous to similar clusters in other species.  

I'm trying to create a definition that will 1) be generalizable, and 2) not require changes with more updates.
The above is what I came out with, would like some input and further workshopping on it as I'm not sure it is the greatest def atm.

**Comment by hkir-dev** [comment]
Definitions column added:
https://github.com/obophenotype/brain_data_standards_ontologies/blob/cross_species/src/patterns/data/default/CCN202002013_class_curation.tsv
https://github.com/obophenotype/brain_data_standards_ontologies/blob/cross_species/src/patterns/data/default/CCN201912131_class_curation.tsv
https://github.com/obophenotype/brain_data_standards_ontologies/blob/cross_species/src/patterns/data/default/CCN201912132_class_curation.tsv

**Comment by shawntanzk** [comment]
Some cross-species terms do have NS-forest markers, for them, ill tag on the last sentence of the definition "These cells are transcriptomically homologous to similar clusters in other species." at the end of the definition to note that instead.

**Comment by shawntanzk** [comment]
For non C type (might be cross species but not specifically, eg non-IT projecting (X-species), or Lower FS Basket cell (non X-species)) - definition will be:

A [PrefLabel] of the Mus musculus primary motor cortex. These cells represent the transcriptomically defined cluster [Cluster ID] in the dataset from the referenced publication. 

eg
A Lower FS Basket cell of the Mus musculus primary motor cortex. These cells represent the transcriptomically defined cluster CS202002013_257 in the dataset from the referenced publication.

**Comment by shawntanzk** [comment]
done

**Comment by patrick-lloyd-ray** [comment]
> These cells represent the transcriptomically defined cluster [cluster ID] in the dataset from the referenced publication. These cells are transcriptomically homologous to similar clusters in other species.

This seems tautologous to me, specifically "These cells are transcriptomically homologous to similar clusters in other species." If the clusters are defined transcriptomically, saying two clusters are similar means they are transcriptomically similar (homologous).

**Comment by shawntanzk** [comment]
> If the clusters are defined transcriptomically, saying two clusters are similar means they are transcriptomically similar (homologous).

I think in this case, while 100% true that it is repeating the same thing, it helps in clarity for the end-user. Saying that they are similar (without the use of transcriptomic) could imply similarities in other ways (eg morphologically, electrophysiological, etc.) which while might be true, we do not have sufficient evidence to back that statement out.  Limiting the scope to only transcriptomically similar would be more honest to the data IMO

**Comment by patrick-lloyd-ray** [comment]
> Saying that they are similar (without the use of transcriptomic) could imply similarities in other ways (eg morphologically, electrophysiological, etc.) which while might be true, we do not have sufficient evidence to back that statement out.

Sure, that makes sense. But the last sentence states that they are similar without the use of 'transcriptomically' as a modifier of 'similar'. 

> These cells represent the transcriptomically defined cluster [cluster ID] in the dataset from the referenced publication. These cells are transcriptomically homologous to similar clusters in other species.

Would moving 'transcriptomically' help? Or would the problem just move from 'similar' to 'homologous'?

> These cells are homologous to transcriptomically similar clusters in other species.

**Comment by shawntanzk** [comment]
actually just talked about this in today's meeting with @dosumis - he made a good point that that statement is kind of not useful in the context of the ontology and also misleading if anything - so we will be removing that from the defs and comments - but totally get your point. I guess the use of the term 'homologous' is tricky in general and perhaps we need to reconsider how we present that to people outside who are not familiar with the data. For now, we just have to depend on the logical axioms to hold this up I guess. An important part would probably be to figure out how to make these meanings clear in the cell type cards

**Comment by patrick-lloyd-ray** [comment]
Sounds like a good plan. 

Thanks, @shawntanzk! Very helpful, as always.
