### ISSUE TITLE
NS-forest annotation property

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#208]
To distinguish NS-forest from Allen markers, we need an annotation property specifically for NS-forest markers. 
This will be in addition the expresses axioms that already exist.

**Comment by hkir-dev** [comment]
http://purl.obolibrary.org/obo/PCL_0010058 "has nsforest marker" annotation property added and minimal markers annotated with it
https://github.com/obophenotype/brain_data_standards_ontologies/blob/pcl_migration/bdso-full.owl

**Comment by shawntanzk** [comment]
I think it has to be an annotation property instead of an object property -> we do not want the child nodes to inherit those properties. 
The NS-forest can be a string with its gene symbol.
The only use for this annotation is for Allen side to present it specifically as NS forest anyway.

**Comment by hkir-dev** [comment]
It is an annotation property https://github.com/obophenotype/brain_data_standards_ontologies/blob/640978468ee903f32b2d43e6afdcb6d91058a8a6/src/ontology/bdso-edit.owl#L43 but seems comment line is wrong, updated all and refreshed the ontology

**Comment by shawntanzk** [comment]
looks good now :) I'm going to close this issue, but do note that we need this as part of dump for allen
