### ISSUE TITLE
Automated obsoletion of old pCL terms

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#216]
Steps needed for obsoletion:
1) add owl:deprecated "true" assertion using this pattern:
AnnotationAssertion(owl:deprecated obo:pCL_XXXXXX "true"^^xsd:boolean)
2) Remove all equivalence axioms
3) Remove all subclass axioms
4) add "obsolete" in front of the rdfs:label (eg "obsolete gamma-glutamyltransferase activity") <- Note: case-sensitive
5) add "OBSOLETE." in front of defintion (eg "OBSOLETE. Catalysis of the reaction: (5-L-glutamyl)-peptide + an amino acid = peptide + 5-L-glutamyl-amino acid.") 
6) add rdfs:comment "this term has been obsoleted and replaced by an updated term from the Brain Data Standards ontology, please see 'term replaced by' axiom to for new term" 
7) add 'term replaced by' axiom that maps to new term following this pattern - the first pCL ID being the one to be obsoleted, the second being the term it is being replaced by:
AnnotationAssertion(obo:IAO_0100001 obo:pCL_XXXXXX "pCL_XXXXXX"^^xsd:string)

**Comment by shawntanzk** [comment]
For mappings (step 7):
1) Create a spreadsheet with the following columns by trying to automatically map synonym (pCL to be deprecated) to prefLabel (in BDSO) 

| deprecated pCL ID | synonym | preferred_name | ID mapped to |
|---|---|---|---|
|pCL_0000370|Astro FGFR3 NWD1|CCDC129-expressing marmoset primary motor cortex astrocyte|pCL_XXXXXXX|

2) @shawntanzk will then fill up the rest that cannot be mapped automatically

**Comment by hkir-dev** [comment]
PCL legacy ontology released: https://github.com/obophenotype/brain_data_standards_ontologies/blob/pcl_migration/pcl-legacy.owl

**Comment by shawntanzk** [comment]
merge legacy into main file -> we need the obsoletion in base file when we export it as a component

**Comment by hkir-dev** [comment]
legacy merged to main (and all_templates.owl) https://github.com/obophenotype/brain_data_standards_ontologies/blob/pcl_migration/bdso-base.owl
plc-legacy.owl is now a component: https://github.com/obophenotype/brain_data_standards_ontologies/blob/pcl_migration/src/ontology/components/pcl-legacy.owl
