### ISSUE TITLE
Integrate new GTF file for human

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#217]
It seems that basically everyone has been using an outdated gtf file and Jeff Goldy finally provided us with the right one that is in NCBI gene format (https://drive.google.com/drive/folders/17WTD9p21aU1oDqVaAj8Z4VZnS6PaY-x3)
We need to do the following to change to that:

- [x] Add gene symbol to gene ID tsv to repo @shawntanzk (I've ran my scrappy R script to extract that out already) 
- [x] Change the NS-forest for both MTG and M1 human to using that on entrez/ncbigene IDs @hkir-dev 
- [x] Change the curated Allen markers to using entres @shawntanzk

**Comment by shawntanzk** [comment]
I have replaced simple_human.tsv with an updated version that uses entrez here https://github.com/obophenotype/brain_data_standards_ontologies/commit/2d5f34a50156a2ee49bdfbe9644af4dded02f50a @hkir-dev could you help follow up with this, changing the file to read the correct columns and read it as entrez etc. please? thanks!

**Comment by shawntanzk** [comment]
I've also changed the human taxonomies (CS1908210 & CCN201912131) to entrez IDs - not sure if you need to change anything so it reads entrez IDs or the name space is enough @hkir-dev thanks :)

**Comment by hkir-dev** [comment]
Marker files, class base template, simple_human.tsv updated, ontology generated: https://github.com/obophenotype/brain_data_standards_ontologies/commit/909142031a7fa5c69bbe22284f627cd73de7f76b
