### ISSUE TITLE
Some terms are old pcl terms are dangling as CL terms

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#222]
Old PCL (legacy) still needs cleaning up by removing some old CL terms 
@hkir-dev not sure if I just manually delete this or how to handle? Is it ok if I leave this to you?

**Comment by hkir-dev** [comment]
Fixed in branch issue_222
We are now deleting all non-pcl classes from the old PCL.

**Comment by shawntanzk** [comment]
Fixed
