### ISSUE TITLE
gene markers need species prefix

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#223]
Currently gene markers are causing duplicate ID failures
this can be fixed by prefixing them with the species they come from
eg lamp5 -> Homo sapien lamp5 
not sure which step is best to add the prefix in, happy to help if need be @hkir-dev

**Comment by hkir-dev** [comment]
Prefixes added: https://github.com/obophenotype/brain_data_standards_ontologies/blob/pcl_migration/src/templates/ensmusg.tsv

**Comment by shawntanzk** [comment]
Fixed
