### ISSUE TITLE
HubMap

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#227]
- [ ] @hkir-dev to use the names here https://docs.google.com/spreadsheets/d/1tK916JyG5ZSXW_cXfsyZnzXfjyoN-8B2GXLbYD6_vF0/edit#gid=1379088218 to match ID with Label name and pcl ID (prefLabel should be the key)
- [ ] @shawntanzk to spot check NS-forest

**Comment by hkir-dev** [comment]
PCL ID column added after the CT/1 columns: [ASCT+B_Tables_Published_v1.0_v1.1 - Brain_v1.1-PCL.xlsx](https://github.com/obophenotype/brain_data_standards_ontologies/files/7933407/ASCT%2BB_Tables_Published_v1.0_v1.1.-.Brain_v1.1-PCL.xlsx)

**Comment by shawntanzk** [comment]
check with Josef how to handle NS-forest @dosumis 
Hold off until above and purls resolve
