### ISSUE TITLE
Inconsistencies in ENSMUSG

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#228]
Currently our mouse marker files have multiple duplicates (1597 errors): 

ERROR	duplicate_label	http://identifiers.org/ensembl/ENSMUSG00000063488	rdfs:label	Mouse Zkscan7
ERROR	duplicate_label	http://identifiers.org/ensembl/ENSMUSG00000111063	rdfs:label	Mouse Zkscan7
ERROR	duplicate_label	http://identifiers.org/ensembl/ENSMUSG00000022361	rdfs:label	Mouse Zhx1
ERROR	duplicate_label	http://identifiers.org/ensembl/ENSMUSG00000116334	rdfs:label	Mouse Zhx1
ERROR	duplicate_label	http://identifiers.org/ensembl/ENSMUSG00000070605	rdfs:label	Mouse Zfp992
ERROR	duplicate_label	http://identifiers.org/ensembl/ENSMUSG00000115857	rdfs:label	Mouse Zfp992

On closer look, some IDs are labelled wrongly 
(eg http://identifiers.org/ensembl/ENSMUSG00000111063 should be Zfp660 but is labeled as Zkscan7) 

With mouse 10x gtf file, only one gene is lacking (AC129186_1), however, that gene was given to us as ensembl:ENSMUSG00000116610 which is Gm49678, furthermore, AC129186_1 doesn’t exist in ensembl. 

So a few things I worry about:

1. Are the ensembl IDs we were given right and do they match up to the HGNC? Which do we follow? 
2. AC129186.1 is in Azimuth, but not  Gm49678 - did they use the same files we are using that might be problematic? Is the ensembl or the HGNC right?

**Comment by hkir-dev** [comment]
Related with this comment https://github.com/obophenotype/brain_data_standards_ontologies/pull/235#issuecomment-996528533 , new ensembl.tsv is in use https://raw.githubusercontent.com/obophenotype/brain_data_standards_ontologies/pcl_migration/src/templates/ensmusg.tsv

**Comment by shawntanzk** [comment]
Keeping this open for this issue to be discussed:

GTF file doesnt match up with ensembl
a worry I have is that AC129186_1 is mapped to ENSMUSG00000116610 which if I search in ensembl comes out as Gm49678 (https://www.ensembl.org/Mus_musculus/Gene/Summary?db=core;g=ENSMUSG00000116610) - I'm guessing its a different version issue but not sure if its a problem when we display it etc.? I assume they are the same gene with different names, but i do not see AC129186.1 on the ensembl page

**Comment by shawntanzk** [comment]
opened new issue for this
