### ISSUE TITLE
NS forest marker set needs a classification

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#246]
We need a grouping term to group the NS forest marker sets
This has been decided as Gene_set_class using a PCL ID for now while we discuss and search for a more permanent term to group them.

**Comment by hkir-dev** [comment]
:PCL_0010003 "Gene Set" class added in branch https://github.com/obophenotype/brain_data_standards_ontologies/blob/markerset_classification/src/ontology/helper.owl#L16

**Comment by shawntanzk** [comment]
SO:0001260 (sequence collection) to be used

**Comment by shawntanzk** [comment]
Fixed
