### ISSUE TITLE
Missing Markers - mouse primary motor cortex

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#25]
Some markers are missing for:

CCN202002013 | Mouse MOp BICCN taxonomy using multiple RNA-Seq datasets

Mapping table = https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/templates/CCN202002013_markers.tsv

e.g. 

Lamp5 Egln3_1 - CS202002013_2 has no entry in the table and so no markers, even though closely related cell types do, e.g. 

![image](https://user-images.githubusercontent.com/112839/105718707-6f3caa80-5f19-11eb-9b76-1850e918c5ce.png)

I also noticed that some of the glutamatergic neurons are referred to be name, e.g. AllenDend:L5 IT Pld5_1, not ID as they should be:

see https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/templates/CCN202002013_markers.tsv#L36

**Comment by BAevermann** [comment]
I think you are still using the original table that was incomplete. We updated that awhile back and should have all markers and cluster names to taxonomy IDs mapped. 

Attached is the updated file. Originally I believe i sent via slack...

b.
[CS202002013_markers.txt](https://github.com/obophenotype/brain_data_standards_ontologies/files/5867531/CS202002013_markers.txt)

**Comment by dosumis** [comment]
Please could you update on GitHub
- Thanks!

**Comment by dosumis** [comment]
https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/templates/CCN202002013_markers.tsv

**Comment by dosumis** [comment]
update: @BAevermann - the pipeline was originally built assuming ROBOT templates as input, deposited in 
[src/templates/](https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/templates/).  However, supporting automated classification by markers, following the taxonomy, will require producing derived templates.  I've therefore decided to keep the marker mapping tables in a separate directory, keeping your format.  Example here:
https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/markers/CS202002013_markers.tsv

Please deposit future marker mapping files here, following this TSV format.
Thanks!
