### ISSUE TITLE
Add code for producing denormalised marker tables, reflecting taxonomy (as source for new Robot templates)

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#26]
**Aim**: Implement the second strategy (Automate via RF markers)  described here: https://docs.google.com/presentation/d/12pbRftZQHdoygp_8gQAOets6TtxsXaRAxEkWCNoh7yc/edit#slide=id.gb8b04e2add_0_43

**Inputs**:  
 - Marker tables are deposited in src/markers
 and follow the naming scheme '<taxonomy_ID>_markers.tsv. e.g. [CS202002013_markers.tsv](https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/markers/CS202002013_markers.tsv)
 - taxonomy JSON file e.g. https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/dendrograms/CCN202002013.json
 
(For ease of processing, it probably makes sense to re-use the existing transformation of dendrograms to nodes and edges: https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/scripts/dendrogram_tools.py#L12)
 
**Output:** new maker table, following the same format as the input marker table, with each node associates with each node associated with a non-redundant list of all markers associated with the term in the input + all markers associated with child terms.  

**Downstream use of output file:** For reference  - this is ***not*** Spec.  This will allow us to roll ROBOT templates specifying EquivalentClass axioms that, with inference provided by OWL reasoning, recapitulate the taxonomy as OWL classification.

e.g. for 

marker file:
a: g1, g2
b: g2, g3
b2: g4, g5
c: g1, g6
d: g1 g7

dendrogram:
a: 
   - b: 
      - b2: 
   - c: 
      - d: 
->

a: g1,g2,g3,g4,g5,g6,g7
b: g2,g3, g4, g5
b2: g4, g5
c: g1, g6. g7
d: g1 g7

The algorithm should allow for the specification of root terms, so that this could be applied to a subtree, e.g. we might wish to specify distinct roots for GABA-ergic and glutamatergic neurons

The algorithm should also allow for an incomplete list of node:gene associations as inputs.  Missing nodes are treated as if having no marker associations.  This will allow for making classes for only some nodes & limiting marker lists.

e.g. 

a: g1, g2
   - b: g2, g3
      - b1: {Node missing from marker mapping}
          -  b2: g4, g5 

-> 

a: g1, g2, g3, g4, g5
   - b: g2, g3, g4, g5
          -  b2: g4, g5 

@BAevermann  - please review.  Does this make sense to you? 

This should be used in a parallel build (branch on this repo) to the one currently being used.

**Comment by dosumis** [comment]
@dosumis to put this in context of build pipeline

**Comment by hkir-dev** [comment]
Development completed in the marker_classification branch
Generated file can be viewed in [updated marker table](https://github.com/obophenotype/brain_data_standards_ontologies/blob/marker_classification/src/test/test_data/CCN202002013_markers_nested.tsv)

**Comment by hkir-dev** [comment]
Observed some inconsistencies in the ex,st,ng markers table

- Redundant id [CS202002013_69] in markers file
- Redundant id [CS202002013_112] in markers file
- Redundant id [CS202002013_111] in markers file
- Redundant id [CS202002013_28] in markers file

and

- CS202002013_235 exists in markers but not in dendrogram.
- CS202002013_233 exists in markers but not in dendrogram.
- CS202002013_232 exists in markers but not in dendrogram.
- L5 IT Pld5_1 exists in markers but not in dendrogram.
- L5 IT Pld5_2 exists in markers but not in dendrogram.
- L5 IT Rspo1_1 exists in markers but not in dendrogram.
- L5 IT Rspo1_2 exists in markers but not in dendrogram.
- L5 IT S100b_1 exists in markers but not in dendrogram.

**Comment by BAevermann** [comment]
It appears you are using the out-of-date marker file. The current location is:

https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/markers/CS202002013_markers.tsv

I removed all duplicate values. 
Not sure about the instances of "exists in markers but not in dendrogram". Need to look into that.

**Comment by BAevermann** [comment]
From the Dendrogram file under src:
<img width="905" alt="Screen Shot 2021-01-27 at 12 20 59 PM" src="https://user-images.githubusercontent.com/32077222/106048851-3ed04a00-609a-11eb-9ac6-6ab34ea5e81f.png">

**Comment by hkir-dev** [comment]
updated the [marker file](https://github.com/obophenotype/brain_data_standards_ontologies/blob/marker_classification/src/test/test_data/CS202002013_markers_nested.tsv)

**Comment by dosumis** [comment]
@BAevermann - so far we're just using the dendrogram JSON file.  The TSV has additional grouping nodes that we haven't yet incorporated.   Looking at your list, some of these look like key nodes.

@jeremymiller - Are the Pvalb and Sst nodes outside of the original, transcriptomics driven clustering?

**Comment by hkir-dev** [comment]
dendrogram [visualisation](https://github.com/obophenotype/brain_data_standards_ontologies/blob/marker_classification/src/test/test_data/CCN202002013.png) added for easier evaluation

**Comment by jeremymiller** [comment]
The Pvalb and Sst nodes include all of the Pvalb and Sst types, respectively.  Since there are a few very distinct types (Pvalb - Chandelier, Sst - Sst Chold) and a few types that are borderline (e.g., Pvalb Gabrg1 and some Sst Th types), the dendrogram is not a perfect representation of this and so there isn't a single node in the tree that includes all of these types (but there IS a row in the nomenclature table for them).

**Comment by dosumis** [comment]
Re-opening because I realised I spec'd this entirely backwards (!)  The child-classes get the denormalised marker set, not the parents.  **Additional requirement**: root node gets no markers; markers on the root node should not be inherited.

So 

marker file:
z: g9, g10
a: g1, g2
b: g2, g3
b2: g4, g5
c: g1, g6
d: g1 g7

dendrogram:
z:
   - a: 
      - b: 
         - b2: 
      - c: 
         - d: 
 
Root node = a

-> 

a: 
b: g2, g3
b2: g2, g3, g4, g5
c: g1, g6
d: g1, g6, g7

**Comment by hkir-dev** [comment]
Behavior change implemented (see [denormalized marker file](https://github.com/obophenotype/brain_data_standards_ontologies/blob/update_issue_31/src/test/test_data/CS202002013_markers_denormalised.tsv))
denormalized marker table building process didn't integrated to the make file, it can be triggered by tests now. Should I add this to the make file?

**Comment by dosumis** [comment]
> Should I add this to the make file?

Yes please.

**Comment by hkir-dev** [comment]
Make file updated but we have two inconsistencies that prevent full automation:

1. This script utilizes marker template from /src/markers/CS202002013.tsv. We don't have marker files for other dendrograms and naming convention is different (CCN vs CS)
2. This script utilizes taxonomy_details.yaml to identify root terms which is specific for CCN202002013.json. Config files for other dendrograms are missing.

**Comment by dosumis** [comment]
Hi @BAevermann  - We're finally reviewing some draft products and have noticed an issue with missing nodes again.

Here's the marker file: https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/markers/CS202002013_markers.tsv
It has 137 entries. 

The full dendrogram has 231 nodes: https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/templates/CCN202002013.tsv

**Comment by BAevermann** [comment]
@dosumis - We didnt run NS-Forest on the entire dendrogram, only those nodes of interest at the time (those that were labelled in the original taxonomy).  This included the leaf nodes and major groupings such as subclasses (VIP, SST, etc..)
