### ISSUE TITLE
Taxonomy Individuals should retain taxonomy node ID (AKA accession) as short form.

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#283]
Dependency - we need an IRI pattern - one that works for new ontologies following CCF2.

Options: 
 - Use PURL under PCL space (as owners of PCL, we have control of this), e.g. 
purl.obolibary.org/obo/pcl/CCN201810310_1

- Something BICAN specific? - or do we want this to be broader?

**Comment by shawntanzk** [comment]
just a heads up - for now ODK doesn't do overly well with non obolibrary purls -> this will change with the new update apparently, but not sure when that will be fully released. 
I don't think it will overly affect this, but just something to be careful about I guess.
Should also be careful with products that deal with base, or any sparql stuff that assumes native = ID space

**Comment by hkir-dev** [comment]
We were previously using accession IDs for IRIs, so don't think it will be a problem.
By the way, we also represent taxonomy itself as an individual (https://www.ebi.ac.uk/ols/ontologies/pcl/individuals?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPCL_0011000). Should we use accession id for those as well?

**Comment by dosumis** [comment]
> By the way, we also represent taxonomy itself as an individual (https://www.ebi.ac.uk/ols/ontologies/pcl/individuals?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPCL_0011000). Should we use accession id for those as well?

Yes.  Definitely.
