### ISSUE TITLE
Migrate pipeline to ODK 1.4

### ISSUE THREAD

**Issue by matentzn** [obophenotype/brain_data_standards_ontologies#286]
I am trying a large scale effort to migrate every ontology under ODK.

**Comment by hkir-dev** [comment]
I will make this upgrade. `bdso.Makefile` is very customized, needs some refactorings

**Comment by hkir-dev** [comment]
Migration completed: https://github.com/obophenotype/brain_data_standards_ontologies/pull/287

**Comment by matentzn** [comment]
How did you solve the unsat issue?

**Comment by hkir-dev** [comment]
Looks like those were my fault during migration. BDSO was using ODK v1.2.32 and the old import mechanism. Some old import files were used in the edit file. I cleaned them and the problem solved: https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/ontology/bdso-edit.owl#L13

**Comment by matentzn** [comment]
Cool thank you!
