### ISSUE TITLE
Write extraction pipeline for BDS subset terms

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#29]
See https://github.com/orgs/obophenotype/projects/3#card-54257903 for example of term tagging.

-  ROBOT QUERY + SPARQL -> list of terms
-  ROBOT extract  (SLME BOT) + list of terms => Ontology slice

Make a gist to store this for now.

**Comment by hkir-dev** [comment]
Extraction pipeline completed: https://gist.github.com/hkir-dev/cc2cdb6bddc6ba8e69ee3862af6794d8
