### ISSUE TITLE
Spec basic curation table that will work for both versions of pipeline.  @dosumis

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#30]
Switch to using IRIs based on accessions.
Equivalent class expressions split out into a separate table.

Simplified curation table (e.g. https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/templates/CCN202002013_class.tsv)

Various aliases should be rolled into a comment in this template.  Comment can make clear type of alias.

**Comment by dosumis** [comment]
STATUS: IN PROGRESS
This aim simplifies the current curation tables, e.g. https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/templates/CCN202002013_class.tsv

**Aim:** A partially filled robot template tsv that can be used to manually curate labels, classification and properties of classes defined with reference to nodes in the taxonomy.  Classes and properties will be linked via subClassOf axioms.

A second template will provide  Equivalent Class definitions for the same terms following one of two patterns 
 Pattern1 : Following https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/templates/CCN202002013_class.tsv
 Pattern2: Link To ticket TBA

Robot template spec:

ID -> IRI of form  http://www.semanticweb.org/brain_data_standards/AllenDendClass_{accession e.g. CS201810310_1}
label: curated field
synonyms_from_taxonomy: Pre-rolled text list field (multiple entries separated by `|`). Source fields.
curated_synonyms: curated text list field (multiple entries separated by `|`)
classification: Curated field
comment: Pre-rolled text from the fields in taxonomy. Recipe
classification_comment: Curated text field
classification_pub: curated text list field (multiple entries separated by `|`)

**Comment by dosumis** [comment]
@hkir-dev - please review

**Comment by hkir-dev** [comment]
Quesitons on curation table:
1. Does "content: curated ..." means template field will be left empty for manual curation or get data from some existing manually curated table?
2. How should we handle empty strings for Synonyms_from_taxonomy, should we ignore? Such as cell_set_additional_alias sometimes has "" as value.

**Comment by hkir-dev** [comment]
curation table updated: [new table](https://github.com/obophenotype/brain_data_standards_ontologies/blob/update_issue_31/src/templates/CCN202002013_class.tsv)
[Equivalent classes template](https://github.com/obophenotype/brain_data_standards_ontologies/blob/update_issue_31/src/templates/CCN202002013_equivalent_reification.tsv) with the reification pattern added.
