### ISSUE TITLE
Spec for Equivalent Class template - marker pattern

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#32]
STATUS: Draft for review.

Aim: Roll Equivalent Class definitions consisting of a conjunction of: Gross cell type; Brain region; Denormalised marker list.  

Configuration:  A list of root nodes & corresponding genus terms (gross cell types).   The root terms are used as input to the script (see #26 ) that generates denormalised markers for each subtree, providing output for populating this table.  Note: the node corresponding the root should **not** have markers associated with it.  The corresponding genus (gross cell types) terms should be applied to all classes in the subtree.  Related ticket:  #33

Header | template_row | content
-- | -- | --
ID | ID | `http://www.semanticweb.org/brain_data_standards/AllenDendClass_{accession e.g. CS201810310_1}`
CLASS_TYPE | CLASS_TYPE | equivalent
Definition | A IAO:0000115 | Automatically rolled text string - see recipe*
Evidence | AI RO:0002558 | IRI of defining individual e.g. `http://www.semanticweb.org/brain_data_standards/AllenDend_CS201810310_1}`
Gross_cell_type |  C % | { CURIE of CL term specified in configuration }
Brain_region | C {R specified in [config](https://github.com/obophenotype/brain_data_standards_ontologies/issues/33)} some % | {Specified in [config](https://github.com/obophenotype/brain_data_standards_ontologies/issues/33)} 
Marker1 |  C expresses some % | { CURIE of ENSEMBL gene term } 
Marker2 |  C expresses some % | { CURIE of ENSEMBL gene term } 
 
...  As many marker columns as the max number of markers specified for any type.  (To check - is it possible to use  `SPLIT ON |`  to limit this to one column?)

\* Draft definition recipe:  "A {Gross_cell_type} with a soma in the {Brain_region}, which expresses: { list of markers delimited by ' and '.}". # Note - slots here should be filled by the rdfs:label of each term.  # push to config?***
\** We need a suitable annotation property here. Not sure what.
\*** We could potentially leave out the definition in an MVP

**Comment by dosumis** [comment]
@hkir-dev  - please review.

**Comment by hkir-dev** [comment]
initial version implemented. Please see the [related file](https://github.com/obophenotype/brain_data_standards_ontologies/blob/update_issue_31/src/templates/CCN202002013_equivalent_markers.tsv)
But not integrated to the make file since further configs required for other dendrograms.
