### ISSUE TITLE
Update taxonomy template

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#34]
**Aim:**  A robot template for generation of OWL taxonomy that preserves the metadata found on nodes in the original taxonomy.

**Spec**: Extend the [current robot template](https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/templates/CCN202002013.tsv) to add the following properties as `http://n2o.neo/custom/`. e.g. `http://n2o.neo/custom/cell_set_preferred_alias`:  
cell_set_preferred_alias , original_label , cell_set_label , cell_set_aligned_alias , cell_set_additional_alias , cell_set_alias_assignee, cell_set_alias_citation.  In the original JSON, multiple entries are separated by a `|`.  These should be split into separate annotations. 

Also store the whole node JSON as a JSON string under `http://n2o.neo/custom/node_metadata`

Example node metadata:

```json
{
                                              "members": 3,
                                              "midpoint": 0.75,
                                              "height": 0.0376,
                                              "label": "",
                                              "edgePar.col": "#000000",
                                              "edgePar.lwd": 2,
                                              "edgePar.conf": 1,
                                              "cell_set_preferred_alias": "",
                                              "original_label": "n11",
                                              "cell_set_label": "RNAseq 002-004",
                                              "cell_set_accession": "CS202002013_127",
                                              "cell_set_aligned_alias": "",
                                              "cell_set_additional_alias": "",
                                              "cell_set_alias_assignee": "Zizhen Yao",
                                              "cell_set_alias_citation": "10.1101/2020.02.29.970558",
                                              "cell_set_structure": "primary motor cortex",
                                              "cell_set_ontology_tag": "UBERON:0001384",
                                              "taxonomy_id": "CCN202002013",
                                              "species": "Mouse",
                                              "modality": "RNAseq",
                                              "_row": "n11"
                                            }
```

**Comment by dosumis** [comment]
@hkir-dev - please review

**Comment by hkir-dev** [comment]
change implemented, please see [new table](https://github.com/obophenotype/brain_data_standards_ontologies/blob/update_issue_31/src/templates/CCN202002013.tsv)

**Comment by hkir-dev** [comment]
observed an nconsistency in the dendorgram json files. In CCN202002013.json property name is "cell_set_additional_alias" but in other jsons it is "cell_set_additional_alias**es**"

**Comment by dosumis** [comment]
According to this https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/doc/dendrogram_spec.md (supplied by Jeremy), it should be plural. As a quick fix, I'd change the keys in CCN202002013.json.  If we continue to use JSON files shared informally with us, we should write a JSON schema validator to automate reports of non-compliant files. This might become unnecessary once we have access to the Neo4J taxonomy database.
