### ISSUE TITLE
Centralise specification of prefixes and OWL entity dependencies

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#35]
Robot templates require curie maps & an input ontology with entities referenced in template strings.

Prefixes can be managed via a JSON-LD context file: http://robot.obolibrary.org/global#prefixes, rather than, as currently, via prefix mapping declarations in build commands. 

[e.g.](https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/ontology/bdscratch.Makefile#L36) 

```make
components/%.owl: ../templates/%.tsv bdscratch-edit.owl
	$(ROBOT) template --input bdscratch-edit.owl --template $< \
    		--add-prefix "BDSHELP: http://www.semanticweb.org/brain_data_standards/helper.owl#" \
    		--add-prefix "AllenDend: http://www.semanticweb.org/brain_data_standards/AllenDend_" \
    		--add-prefix "skos: http://www.w3.org/2004/02/skos/core#" \
    		annotate --ontology-iri ${BDS_BASE}$@ \
    		convert --format ofn --output $@
```

ontology entity requirements are currently maintained by hand in `bdscratch-edit.owl` but we should probably have something more efficient.

**Comment by dosumis** [comment]
Hi @matentzn, for ROBOT templates to build, we need an ontology with declarations and labels for the the entities references in ROBOT template strings.  Right now I'm putting these into the editor's file, but would prefer not to make declarations there, and really don't want to be asserting labels outside of their source ontologies.  Is there a better/standard way to manage this with ODK builds dependent on ROBOT templates?

**Comment by matentzn** [comment]
There is no perfect solution; two options:
1. you embed the term right in the template. So 
```
RO:0000052	part_of
```

Downside: that label gets merged in. What I do is couple that with `remove --term RO:000062 --select annotations` pipe right before the pipeline is written out.

2. you create an ontology just with the signature and labels you need for the template and mix it in (`-i labelont.owl`) the process.

I suggest try option 1!

**Comment by dosumis** [comment]
Hi @matentzn, wondering what you mean by this:

> you embed the term right in the template. So
> RO:0000052	part_of

Do you mean add a ROBOT (?) template that specifies labels for properties?

**Comment by matentzn** [comment]
Any template will have and ID column, right? you can add the ID for the relationship you need as well. Example:

| ID | LABEL | .... | 
| -- | ------ | ---|
| ALLEN:001 | neuron1  | ... |
| ALLEN:002 | neuron2 |  ... |
| RO:001 | part_of | ... |

**Comment by matentzn** [comment]
the cleaner way to do this is to have an external owl file (or template!) with the labels and feed it to the template generation process. That way the `bad` label does not leak into the ontology!
