### ISSUE TITLE
Add schema validation script

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#37]
JSON _schema in src/config/config_schema.json is designed to validate metadata about Allen Taxonomies.

Metadata is stored as YAML (easier for non-technical people to curate than JSON) - each element in list in dendrograms/taxonomy_details.yaml should validate against schema when converted to JSON.

We need schema validation hooked up to GitHub actions CI. 

Some examples of validator scripts I've worked on

https://github.com/HumanCellAtlas/metadata-schema/blob/master/src/schemas_are_valid_json.py
https://github.com/INCATools/dead_simple_owl_design_patterns/blob/master/src/simple_pattern_tester.py

Schema is very simple and uses no imports of external schema modules, so something simple will suffice.

**Comment by dosumis** [comment]
TBD: Currently I'm assuming one taxonomy.yaml with a list of taxonomy details.  Might be better for usability to have one per taxonomy. 
Schema and example are currently on branch https://github.com/obophenotype/brain_data_standards_ontologies/pull/36

**Comment by hkir-dev** [comment]
[Schema validator](https://github.com/obophenotype/brain_data_standards_ontologies/blob/config/src/config/config_schema_validator.py) added. 
Updated the config file to define a valid YAML config list.
In accordance with the yaml, updated the schema json file.
Github actin linked to the script.
