### ISSUE TITLE
Update build pipeline to support denormalized markers

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#42]
2 branches needed

## Branch 1: EquivalentClass definitions link directly to anatomical individuals
Built from: 

TEMPLATE_FILES = $(patsubst %, ../templates/%.tsv, $(JOBS)) # Taxonomy as OWL individuals
TEMPLATE_CLASS_FILES = $(patsubst %, ../templates/%_class.tsv, $(JOBS))  # Partially curated class files
MARKER_FILES = $(patsubst %, ../templates/%_markers.tsv, $(JOBS)) # Normalised markers
EQUIVALENT_CLASS_REIFICATION_FILES = $(patsubst %, ../templates/%_equivalent_reification.tsv, $(JOBS)) #EquivalentClass axioms - generated

## Branch2: EquivalentClass definitions used denormalised markers

TEMPLATE_FILES = $(patsubst %, ../templates/%.tsv, $(JOBS)) # As branch 1
TEMPLATE_CLASS_FILES = $(patsubst %, ../templates/%_class.tsv, $(JOBS)) # Partially Curated, shared with branch 1
MARKER_DENORMALIZED_FILES = $(patsubst %, ../templates/%_markers_denormalized.tsv, $(JOBS)) # EquivalentClass axioms

**Comment by dosumis** [comment]
The Makefile under dendograms, which build ROBOT templates can be the same in both branches, building all templates.  The 2 branches should differ in the main build makefile: https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/ontology/bdscratch.Makefile reflecting the different templates used to generate OWL for the final product.

**Comment by dosumis** [comment]
To build

cd src/ontology
sh ./run.sh make prepare_release MIR=false

**Comment by hkir-dev** [comment]
Related braches created:
Branch 1: https://github.com/obophenotype/brain_data_standards_ontologies/tree/ec_individuals
Branch 2: https://github.com/obophenotype/brain_data_standards_ontologies/tree/ec_denormalised_markers

**Comment by BAevermann** [comment]
Hey David!

I was wondering what the status of Branch2 is? I was looking to get involved in extending the templates to generate marker derived definitions of form used in the pCL. 

Thanks!

b.

**Comment by dosumis** [comment]
Hi @BAevermann - see comment on https://github.com/obophenotype/brain_data_standards_ontologies/pull/41
