### ISSUE TITLE
Include DOSDP template for definition and (perhaps) label

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#43]
We already have a draft patten here: https://github.com/obophenotype/brain_data_standards_ontologies/pull/41/files

This needs to be adapted to add a data_var that we can use to incorporate a list of marker names. 
OWL generation will be driven by a TSV in https://github.com/obophenotype/brain_data_standards_ontologies/tree/master/src/patterns/data/default
This will include a list of markers.  Labels can be found in: https://raw.githubusercontent.com/obophenotype/brain_data_standards_ontologies/master/src/templates/ensmusg.tsv

@dosumis to provide TSV spec & details of how to add new dosdp patterns to the build.

**Comment by dosumis** [comment]
@matentzn where can I find doc on how to turn on build from dosdp in ODK?

**Comment by matentzn** [comment]
add 

```
use_dosdps: TRUE
```

To your config and `sh run.sh make update_repo` should do it!

**Comment by dosumis** [comment]
TODO - @dosumis  to provide accompanying tsv spec to drive built.  This will live in https://github.com/obophenotype/brain_data_standards_ontologies/tree/master/src/patterns/data/default and have the same name as the dosdp.yaml file - part from the the file extension.

TSV will have columns:

defined_class: Curie of class being defined
+ additional columns for name for all vars in the pattern.

For maker list strings, use this TSV for name lookup: https://raw.githubusercontent.com/obophenotype/brain_data_standards_ontologies/master/src/templates/ensmusg.tsv

**Comment by dosumis** [comment]
Columns:
* defined_class: CURIE of BDS class
* gross_cell_type: from config
* taxon: from config
* brain_region: from config
* denorm_marker_list:   A string = A list of maker names delimited by ', ' - from the denormalised maker file.
* minimal_marker_list:  A string = A list of maker names delimited by ', ' - from the original marker list

For maker list strings, use this TSV for name lookup: https://raw.githubusercontent.com/obophenotype/brain_data_standards_ontologies/master/src/templates/ensmusg.tsv

**Comment by hkir-dev** [comment]
@dosumis please review: https://github.com/obophenotype/brain_data_standards_ontologies/blob/DOSDP_patterns/src/patterns/data/default/brainCellRegionMarker.tsv
