### ISSUE TITLE
Extend config YAML to include non neural cell types

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#45]
Use PCL for inspiration for what cell types to cover: 

https://bioportal.bioontology.org/ontologies/PCL/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPCL_0000371

Config file is here: 

Edit on branch.  See this PR: https://github.com/obophenotype/brain_data_standards_ontologies/pull/41

@shawntanzk

**Comment by shawntanzk** [comment]
Need to add Meis2 into CL - @shawntanzk will go read up and figure out

**Comment by shawntanzk** [comment]
@dosumis I just realised I added the changes to config branch (I wrote to do it there on my own notes), but I've also checked the DOSDP_patterns branch from the PR above, and it doesn't have the yaml file. Do let me if I should continue on the config branch. 

I've also had some stuff that needs to be discussed that I wrote on the commit https://github.com/obophenotype/brain_data_standards_ontologies/commit/4b5eb33d6373d2f4300fcffba95c294c8cd8b090

**Comment by shawntanzk** [comment]
> Need to add Meis2 and VLMC into CL - @shawntanzk will go read up and figure out

I think these cells need to be defined (even in CL) transcriptomically, along with SMC/Peri and Microglia/PVM. Perhaps we get the minimal required genes for the forest output and use them to describe these cells in CL (manually for now) so we can add them to the yaml file?

**Comment by dosumis** [comment]
You can add to config.  We need to merge down.  You can map to a more general class for non-neural cells for now.  We can discuss whether to add cortical subtypes.

**Comment by shawntanzk** [comment]
Not quite sure what you mean by mapping them to more general class - these are upper classes as is already, but looking at the literature, the grouping seems to be fully transcriptomics (eg microglia/PVM are two separate types, but grouped transcriptomically together, or Meis2 appears to be in GABA and Glut neurons too, but seem to have a subgroup in non-neuronal cells).

**Comment by dosumis** [comment]
The aim here is to specify a set of root nodes we can use for generating finer-grained, marker-based definitions & link these to general genus classes in CL.  I think we need to discuss whether we want/need to take higher level transcriptomic groupings into account.  Just concentrate on the nodes where we can get a 1:1 mapping with a general class in CL.  It looks like this can be done for oliogdendrocytes, microglia, oligodendrocyte precursors, endothelial cells, brain pericyte.  Find the right SMC cell might require some discussion.  Node for PVM  on it's own is not in dendrogram - but [is in table](https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/dendrograms/nomenclature_table_CCN202002013.csv#L238) (which we will map in later.)

vascular leptomeningeal cell (VLMC) + Meis cells (GABA-ergic neurons?) - some more work required to add research & add terms to CL for these.

![image](https://user-images.githubusercontent.com/112839/109967014-d0aa2300-7ce8-11eb-85ec-8714f69d9a9f.png)
