### ISSUE TITLE
GABAergic CL mapping

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#46]
On CS202002013_123 (GABAergic), I've current mapped CL:0000617 (GABAergic neuron) as it's the highest level/most generic. It can also be CL:0011005 (GABAergic interneuron) or CL:0010011 (cerebral cortex GABAergic interneuron). I think it depends on the list of markers and how generalizable they are?

**Comment by dosumis** [comment]
I think 'GABAergic interneuron' should be sufficient to line up with the terms in CL (they will get an inference to cortical from the soma location axiom).
