### ISSUE TITLE
Generate report of key marker expression for GABAergic clusters

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#54]
e.g. Is LAMP5 expressed in all subclusters of the LAMP5 node (CS202002013_125), and a what level (some stats?  % cells in node, mean expression level?)

Highest priority = genes named in grouping clusters of GABAergic neurons
LAMP5 
~~alpha7~~ 
Pvalb
VIP
Sst
Scng

But we should cover all genes in names attached to clusters in the dendrogram

**Comment by jeremymiller** [comment]
(Can you clarify what the specific ask is here?  I don't think alpha7 is a gene...)

**Comment by dosumis** [comment]
Took this from [alpha7 Lamp5 GABAergic cortical interneuron](http://ec2-18-188-87-230.us-east-2.compute.amazonaws.com:8080/ontologies/bds2/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_4023010&viewMode=PreferredRoots&siblings=false) -  text def has "strongly labelled for α7 nAChRs" - but I guess may be antibody / multiple genes.

**Comment by dosumis** [comment]
@jeremymiller - have updated spec a bit to clarify.  I think you mentioned being able to provide a heat map of expression of key marker genes for all nodes.  That would work nicely.  The aim here is to judge whether transcriptomics grouping nodes like the one named Lamp5 should be Lamp5-like in the ontology.

**Comment by jeremymiller** [comment]
If you or @BAevermann provide me with a list of markers, then I can provide the heatmap.  My guess is a list of these NSForest markers (or other markers) already exist somewhere.  Thanks!

**Comment by dosumis** [comment]
These are not NSForest markers, they are genes in names of clusters/dendrogram nodes.

Could you start with 
LAMP5, Pvalb, Vip, Sst & Scng.  If you need ensembl IDs, we have them here: https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/templates/ensmusg.tsv

**Comment by dosumis** [comment]
@shawntanzk  - can you provide a complete list of genes names in cell-set preferred aliases?

**Comment by shawntanzk** [comment]
whats the best format? I already have it sort of written out when looking at developmental nature of genes, but thats in a word document

**Comment by jeremymiller** [comment]
Any text-based format (including a word document) is fine.

**Comment by shawntanzk** [comment]
[Gene Markers.docx](https://github.com/obophenotype/brain_data_standards_ontologies/files/6191112/Gene.Markers.docx)
Sure thing, see attached for word document with list of markers

**Comment by dosumis** [comment]
Thanks!  So - for the GABAergics it looks like there's a reasonable case for making VIP-like and Lamp5-like grouping classes, as they both subsume a couple of leaf nodes where mean expression and fire plot have expression at or barely above level seen in other GABAergics.   We could still potentially have CL GABAergic classes defined by Vip and Lamp5 expression, populated based on assertions of expression on leaf nodes.  OTOH, sst looks safe &  sncg also probably OK (overall expression is much lower).  @jeremymiller - will heatmaps for key markers such as these be available in cell type cards?  I'll be more comfortable with crude qualitative assertions if users can see the real data too.

**Comment by jeremymiller** [comment]
We will be including marker gene plots as part of the cell type cards, although the specifics of which genes will be included could be adjusted to address these kinds of issues.  Nik Jorstad is the content owner for this.

**Comment by shawntanzk** [comment]
@dosumis have just gone through the fireplot and trimmed mean heatplot and honestly only lamp5 really has an issue with Lamp5 Egln3_1 expressing Lamp5 at a level that is really close to baseline. 
VIP has a couple that have low VIP expression which get wiped out in the trimmed means plot, but you can see the difference in the fireplot. 
Interesting thing from this for me is that there are nodes that express other classes marker - eg Sncg Col14a1 clearly expresses Vip. 
On the contrary, nodes like Sst Pvalb Etv1 barely expresses Pvalb (though it is higher than the other Sst, just really low amounts - might need to clarify what the values on the plots are actually to resolve this)

**Comment by dosumis** [comment]
>but you can see the difference in the fireplot.

But that fire plot shows that very few cells express above baseline in the cluster for those 2 cases.  I'd say these are at least borderline worth getting more opinions on - or coming up with some way to derive cutt-offs from the data.

> Interesting thing from this for me is that there are nodes that express other classes marker - eg Sncg Col14a1 clearly expresses Vip.

Another good reason to make a VIP-like class with clear tagging that it is defined by transcriptomics.  A property based classification + some automated call based on tresholds might reasonably pull this additional node under a node defined as VIP expressing GABAergic.

**Comment by dosumis** [comment]
@shawntanzk  - might be worth talking with mouse phenomics group at EBI.  They have lots of experience with designing pipelines for automating extraction ontology assertions from data.

**Comment by shawntanzk** [comment]
I do like the idea of finding some cut-offs from the data and doing automated call based on the threshold - we should get some experts input on this, will add it to my notes and see if we can figure this out.

> might be worth talking with mouse phenomics group at EBI.

Happy to, would you mind helping connect me with them? Thanks
