### ISSUE TITLE
Checks to run on submitted marker files

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#56]
Marker files are submitted under `src/markers/`

Files must be named {taxonomy_id}_markers.tsv - any other name will prompt an error  # HARD FAIL

3 columns  - headers and contents as follows # HARD FAIL

Taxonomy_node_ID | clusterName | Markers
-- | -- | --
   CS202002013_123 | GABAergic | ensembl:ENSMUSG00000070880\|ensembl:ENSMUSG00000098326
   CS202002013_179 | Glutamatergic | ensembl:ENSMUSG00000053025\|ensembl:ENSMUSG00000032503

### content checks:
All dendrogram nodes must be present # WARNING
`Taxonomy_node_ID` must be valid # HARD FAIL
`clusterName` must(?) match clusterName in dendrogram # WARNING
` Markers` must match regex `.+\:.+` with multiple entries delimited by `|`.    # HARD FAIL

Checks for these should be added to GitHub actions - running under CI but also as an independent test - ideally with email.  Otherwise just do via PRs.

**Comment by dosumis** [comment]
(this should become a spec/SOP doc).

**Comment by hkir-dev** [comment]
Error/Warning check levels added. Now we hard fail only in one check:
> Taxonomy_node_ID must be valid # HARD FAIL

```
 === Marker Nodes' Dendrogram Existence Checks :
Invalid Taxonomy_node_ID 'CS202002013_235' in the marker file (CS202002013_markers.tsv). Id not exist in the dendrogram.
Invalid Taxonomy_node_ID 'CS202002013_233' in the marker file (CS202002013_markers.tsv). Id not exist in the dendrogram.
Invalid Taxonomy_node_ID 'CS202002013_232' in the marker file (CS202002013_markers.tsv). Id not exist in the dendrogram.
Invalid Taxonomy_node_ID 'CS202002013_250' in the marker file (CS202002013_markers.tsv). Id not exist in the dendrogram.
```
related [github action](https://github.com/obophenotype/brain_data_standards_ontologies/runs/2589710771?check_suite_focus=true)

**Comment by hkir-dev** [comment]
All updates completed and merged to master.
