### ISSUE TITLE
Some leaf nodes have marker sets that do not uniquely identify them 

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#59]
If I understand correctly, [this table](https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/markers/CS202002013_markers.tsv) is meant to provide marker sets that can reliably distinguish each cluster (dendrogram node) from all others.  This is not always the case.  

These are both leaf nodes:

Taxonomy_node_ID | clusterName | Markers Delimited
-- | -- | --
CS202002013_28 | Sst Chodl | ensembl:ENSMUSG00000029361
CS202002013_8 | Lamp5 Lhx6 | ensembl:ENSMUSG00000110002\|ensembl:ENSMUSG00000029361

ENSMUSG00000029361 = Nos1

![image](https://user-images.githubusercontent.com/112839/111304011-210c7380-864d-11eb-8392-ec33f9deb1bb.png)

The single marker for  `Sst Chodl`  - Nos1  is shared with the markers for  `Lamp5 Lhc6` so Nos1 cannot be used to distinguish the two and with OWL reasoning, the former becomes a superclass of the latter.

**Comment by dosumis** [comment]
CC @shawntanzk

**Comment by BAevermann** [comment]
However the denormalized string of marker genes should be unique? Since these have different parent nodes?
We didn't have a "must be unique in dataset" criteria as some marker genes are very specific to one or two cell types. Interestingly, these cell types are often in different parts of the taxonomy, for example there are are markers that are very binary for two clusters: one of which in inhibitory and one that excitatory.

**Comment by dosumis** [comment]
> However the denormalized string of marker genes should be unique?

If we had the intermediate nodes, which we don't in this case.  Note - we only start taking demormalised markers from one step down below the various root nodes we specify & Sst Chod1 is 

> We didn't have a "must be unique in dataset" criteria as some marker genes are very specific to one or two cell types.

I understand that each marker doesn't need to be unique to the dataset, but are you saying the combination of markers doesn't need to be either?   In a case where RF just => one marker, (as for Sst Chod1) then it can't be useful on it's own for distinguishing a cell type if it is also a marker for other cell types.  Am I missing something?

**Comment by dosumis** [comment]
Notes from discussion on call: 

This can happen when the number of cells in one of the clusters is small.  A single marker might reliably identify cells in cluster X 98% of the time when less than 2% of all cells are in cluster Y.  
Make rule that single markers are not allowed.  This may not be perfect, but it is likely to significantly reduce the problem.  
Would it be possible to eliminate marker sets that reliably assign to other clusters?

**Comment by BAevermann** [comment]
Adding the Chodl gene to the marker Nos1 only slightly decreases the f-beta score (0.96 for 1 marker to 0.93 with 2 markers) so this is doable.  

Do we want to add it directly the to file on github?

**Comment by dosumis** [comment]
> Adding the Chodl gene to the marker Nos1 only slightly decreases the f-beta score (0.96 for 1 marker to 0.93 with 2 markers) so this is doable.

> Do we want to add it directly the to file on github?

Can this be automated? Better to have a rule that stops this from happening than to have to manually fix.
