### ISSUE TITLE
Indexing on exact synonyms is broken on AWS OLS instance

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#65]
e.g. try 'Lamp5 Lhx'

It looks like we have the correct config here:
https://github.com/obophenotype/ontotools-docker-config/blob/master/config/ols-config/ols-config.yaml

1. Check that annotation_properties are set correctly in source files.
2. If 1 not problem, check spec / ask James Mclaughlin for help.

**Comment by hkir-dev** [comment]
In the BDS ontology we use "http://www.geneontology.org/formats/oboInOwl#has_exact_synonym"
But OLS using (and the correct one is) "http://www.geneontology.org/formats/oboInOwl#hasExactSynonym"

Confusion caused by the label
> <owl:AnnotationProperty rdf:about="http://www.geneontology.org/formats/oboInOwl#hasExactSynonym">
       <rdfs:label xml:lang="en">has_exact_synonym</rdfs:label>
        <rdfs:subPropertyOf rdf:resource="http://www.geneontology.org/formats/oboInOwl#hasSynonym"/>

**Comment by dosumis** [comment]
Well spotted.  Please switch.

**Comment by hrshdhgd** [comment]
Please let me know when to redeploy.

**Comment by hkir-dev** [comment]
@hrshdhgd master branch updated. We can redeploy

**Comment by hrshdhgd** [comment]
Deployed!
