### ISSUE TITLE
Display both branch builds on OLS

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#68]
- id: bds1
    preferredPrefix: BDS
    title: BDS Ontology
    description: BDS ontology - marker based
    uri: https://raw.githubusercontent.com/obophenotype/brain_data_standards_ontologies/master/bdscratch-full.owl

 - id: bds2
    preferredPrefix: BDS
    title: BDS Ontology
    description: BDS ontology - taxonomy based
    uri: https://raw.githubusercontent.com/obophenotype/brain_data_standards_ontologies/ec_individuals/bdscratch-full.owl

(Related task - update preferred roots)

**Comment by hkir-dev** [comment]
@hrshdhgd We want to present two different versions of the BDS ontology at the same time. For this purpose, I have updated the related [config file](https://github.com/obophenotype/ontotools-docker-config/blob/master/config/ols-config/ols-config.yaml).

Can we restart or re-deploy the OLS to see its effect? Thanks,

**Comment by hrshdhgd** [comment]
Done!
