### ISSUE TITLE
Generate report of patch-seq classes in CL for review by Allen

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#70]
This should be a spreadsheet built from OWL input + set of specified nodes for review.  It should be relatively straightfoward to generate csv using `ROBOT report` + SPARQL.

@shawntanzk to provide spec for columns + inputs
Inputs:
 * List of IDs
 * cl.owl (if prepub, @shawntanzk will provide)

**Comment by hkir-dev** [comment]
I have prepared a xlsx version but I used Libreoffice to generate it. Multiple values are seperade with '|'
[review.xlsx](https://github.com/obophenotype/brain_data_standards_ontologies/files/6188731/review.xlsx)

Altrnatively I have generated in csv (comma seperated, not tab) format
[review.zip](https://github.com/obophenotype/brain_data_standards_ontologies/files/6188737/review.zip)

Also in [share point](https://emblebi-my.sharepoint.com/:x:/g/personal/hkir_ebi_ac_uk/EeN--mvuw5FJsBBLmY8wvOoBEiVXCdWbHkdE6J26ou0o1A?e=ecoP0e)

**Comment by dosumis** [comment]
@hkir-dev - that was fast!  I think we need a version limited to terms in_subset: BDS_subset.
@shawntanzk  - Can you have a think about what columns you'd like for useful feedback + what guidance you'd like to give reviewers regarding what feedback you'd like?  Might be useful to chat with Clare at FB about her experience with this approach.

**Comment by shawntanzk** [comment]
@dosumis oh I was thinking since its just two reviewers atm, just to add a column with my remarks (if any) and a column blank for theirs. Happy to chat with Clare at FB - would you mind helping me get connected to her on slack? thanks

**Comment by hkir-dev** [comment]
Filtered by sub set
[review2.xlsx](https://github.com/obophenotype/brain_data_standards_ontologies/files/6189183/review2.xlsx)
[review2.zip](https://github.com/obophenotype/brain_data_standards_ontologies/files/6189184/review2.zip)
[share point](https://emblebi-my.sharepoint.com/:x:/g/personal/hkir_ebi_ac_uk/EeMijsa4tUNFtaEGsOlL-10BonZtlVSZCzeInWiQfjaGrQ?e=a1ve6K)
related [query](https://gist.github.com/hkir-dev/0847401dbdc57767ce8d64f249d7f85a)

**Comment by shawntanzk** [comment]
perfect! I'll add the prepub ones in and get the file ready to send out :)

**Comment by shawntanzk** [comment]
I've done up a [google sheets ](https://docs.google.com/spreadsheets/d/1gQzl_lLK-QgTGeb7ltZ37xCpdMb8vrB2SjSyI0KZAT4/edit?usp=sharing)of this. I've put it as comment only, and so people can just comment on the appropriate cell and it wouldnt change anything (including current defs) - think it might be smart to leave it that way so that we dont miss any changes.

**Comment by shawntanzk** [comment]
@dosumis I've written up a readme and placed it in the google sheets (think this is the best way so we can send it out more easily). Do let me know if its all good, and if so, happy for it to be sent out. 

Thanks
