### ISSUE TITLE
OWL for loading to VFB-Neo4j

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#71]
The VFB OWL2NEO representation ignores EquivalentClass axioms and so drops the relationship between classes and dendrogram node individuals in the OWL file following the reification pattern.  We can get around this by using [ROBOT relax](http://robot.obolibrary.org/relax) prior to loading.

**Comment by hkir-dev** [comment]
Realx ontology added https://raw.githubusercontent.com/obophenotype/brain_data_standards_ontologies/ec_individuals/bdscratch-relax.owl
