### ISSUE TITLE
Extend taxonomy_details.yaml with non-taxonomy roots

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#72]
Background:  We need a way to map additional "nodes" required to group types in ways not derived from transcriptomics data.  The node IDs in question live in TSVs that extend the node set specified in the taxonomy (nomenclature_table_{taxonomy_id}.tsv.  To achieve this we will extend 
taxonomy_details.yaml (& the accompanying JSON schema spec) to add

```yaml
non_taxonomy_roots:
    - Node: CS202002013_nnn
       Cell_type: CL:nnnnnnn
```

Check:  The node specified should be in nomenclature_table_{taxonomy_id}.tsv but *not* in the dendrogram.  Fail if not true.

nomenclature_table_{taxonomy_id}.tsv has the column: child_cell_set_accessions.  This has a list of dendrogram node IDs which we need to use to add classifications.  We will ignore root nodes.  These classifications should be added via (yet another) ROBOT template

non_taxonomy_classification.tsv:

 ID | Classification
-- | -- 
 ID | SC %
http://www.semanticweb.org/brain_data_standards/AllenDendClass_CS202002013_232 | CL:4030127

One row per Pipe seperated ID in `child_cell_set_accessions`

 - [x] Update JSON schema spec to allow new keys @hkir-dev 
 - [x] Update taxonomy_details.yaml with cell type mappings @shawntanzk 
 - [x] Implement build @hkir-dev

**Comment by hkir-dev** [comment]
First version of the [template](https://github.com/obophenotype/brain_data_standards_ontologies/blob/non_taxo_roots/src/templates/nomenclature_table_CCN202002013.tsv) generated. Current questions are:

- Can a child have multiple classifications? Should we only select the lowest ancestor or having both is ok?
Child CS202002013_114 has multiple classifications: CL:0000881 and CL:0000125
Child CS202002013_115 has multiple classifications: CL:0000881 and CL:0000125
Child CS202002013_116 has multiple classifications: CL:0000881 and CL:0000125
Child CS202002013_30 has multiple classifications: CL:4023017 and CL:4023027
Child CS202002013_31 has multiple classifications: CL:4023017 and CL:4023027
Child CS202002013_32 has multiple classifications: CL:4023017 and CL:4023027
Child CS202002013_70 has multiple classifications: CL:4023008 and CL:4023045
Child CS202002013_71 has multiple classifications: CL:4023008 and CL:4023045
Child CS202002013_72 has multiple classifications: CL:4023008 and CL:4023044
Child CS202002013_73 has multiple classifications: CL:4023008 and CL:4023044

- Should all children have a classification?
Not annotated nomenclature child: CS202002013_27
Not annotated nomenclature child: CS202002013_61
Not annotated nomenclature child: CS202002013_64
Not annotated nomenclature child: CS202002013_62
Not annotated nomenclature child: CS202002013_11
Not annotated nomenclature child: CS202002013_9
Not annotated nomenclature child: CS202002013_19
Not annotated nomenclature child: CS202002013_3
Not annotated nomenclature child: CS202002013_67
Not annotated nomenclature child: CS202002013_2
Not annotated nomenclature child: CS202002013_4
Not annotated nomenclature child: CS202002013_12
Not annotated nomenclature child: CS202002013_14
Not annotated nomenclature child: CS202002013_89
Not annotated nomenclature child: CS202002013_60
Not annotated nomenclature child: CS202002013_17
Not annotated nomenclature child: CS202002013_10
Not annotated nomenclature child: CS202002013_65
Not annotated nomenclature child: CS202002013_18
Not annotated nomenclature child: CS202002013_20
Not annotated nomenclature child: CS202002013_5
Not annotated nomenclature child: CS202002013_68
Not annotated nomenclature child: CS202002013_90
Not annotated nomenclature child: CS202002013_1
Not annotated nomenclature child: CS202002013_15
Not annotated nomenclature child: CS202002013_7
Not annotated nomenclature child: CS202002013_69
Not annotated nomenclature child: CS202002013_16
Not annotated nomenclature child: CS202002013_8
Not annotated nomenclature child: CS202002013_66
Not annotated nomenclature child: CS202002013_13
Not annotated nomenclature child: CS202002013_59
Not annotated nomenclature child: CS202002013_63
Not annotated nomenclature child: CS202002013_6
Not annotated nomenclature child: CS202002013_26
Not annotated nomenclature child: CS202002013_58

**Comment by dosumis** [comment]
> * Can a child have multiple classifications?

Yes

> * Should all children have a classification?

The table should follow the same rules as we use elsewhere for deciding whether to generate and annotate a class (current rules: child of root with cell_set_preferred_alias)

**Comment by hkir-dev** [comment]
Related ontology generated: https://raw.githubusercontent.com/obophenotype/brain_data_standards_ontologies/non_taxo_roots/src/ontology/components/nomenclature_table_CCN202002013.owl

**Comment by dosumis** [comment]
Reviewed: https://raw.githubusercontent.com/obophenotype/brain_data_standards_ontologies/3328efaa238c28400ea61cdeff8d9e6be4158bf1/bdscratch-full.owl

All looks good apart from template needing rename -> 

{taxonomy_id}_non_taxonomy_classification.tsv
