### ISSUE TITLE
Extend equivalent_reification.tsv to add 'subclassOf R Value I axioms

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#74]
Motivation:

*  Neo4j only displays simple subClassOf axioms in its graph, where simple = R {quantifier} Entity
*  ROBOT relax will not relax: EC: C and R value I to SC: C + SC: R value I. (We should probably add a ticket to request that it does)

Spec:

ID | Exemplar | Exemplar_SC 
-- | -- | --
  ID | EC CL:0000003 and 'has_exemplar' value %  | SC 'has_exemplar' value %
  http://www.semanticweb.org/brain_data_standards/AllenDendClass_CS202002013_124 | AllenDend:CS202002013_124 |  AllenDend:CS202002013_124

**Comment by hkir-dev** [comment]
[temaplate](https://github.com/obophenotype/brain_data_standards_ontologies/blob/ec_individuals/src/templates/CCN202002013_equivalent_reification.tsv) updated
