### ISSUE TITLE
Improve representation of dendrogram

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#76]
Browsing taxonomy on Neo is not very easy right now

![image](https://user-images.githubusercontent.com/112839/112608700-8c570200-8e12-11eb-8dcb-424248353b63.png)

We could improve by 

(a) Improving the label recipe:

```py
if cell_set_preferred_alias:
       rdfs_label =   "{cell_set_preferred_alias} - {cell_set_accession}"
else:
       rdfs_label =   "{cell_set_label} - {cell_set_accession}"
```

(b) Extending the Neo:label recipes to cover dendrogram individuals.  This is not completely straightforward, as dendrogram nodes are not modelled as instances of cell type classes and there is no relationship from dendrogram node to Class (only the reverse).  As a result, we can't use a DL class expression to label these nodes.  We could use SPARQL though.

Options: 
* Add reciprocal (exemplar_of) edge between individual and class (I exemplar_of some C), then specify with simple class expression (e.g. 'exemplar of' some 'GABAergic neuron').  I don't think the existential restriction makes much sense, but I don't see any obvious downside)
* Use SPARQL pattern matching (assuming the SPARQL we use supports transitivity).  Deposit SPARQL [here](https://github.com/obophenotype/bds-pipeline-config/tree/main/config/dumps/sparql)

**Comment by dosumis** [comment]
Some more notes: 

A direct relationship *from* dendrogam node to *class* would have the advantage of making direct OWL queries for dendrogram nodes possible.

**Comment by hkir-dev** [comment]
[Query](https://github.com/obophenotype/bds-pipeline-config/blob/main/config/dumps/sparql/construct_exemplar_of.sparql) added to the pipeline.
- Should we only look for the sub-classes of the CL_0000000
- Or should we apply a SPARQL url filter to only construct links for the terms from "http://www.semanticweb.org/brain_data_standards/" domain?

**Comment by dosumis** [comment]
Change of plan:

We should add the reverse relationship using ROBOT templates:

The taxonomy template () should get an additional column:

TI % some BDSHELP:exemplar_of %

This should only be filled for classes we are adding.

**Comment by hkir-dev** [comment]
Related [pull request](https://github.com/obophenotype/brain_data_standards_ontologies/pull/82) created
