### ISSUE TITLE
Extend _class template to allow curation of markers 

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#78]
Additional columns to add to the _class template

Expresses | Expresses_comment | Expresses_pub
-- | -- | --
 SC 'expresses' some % SPLIT=\| | >A rdfs:comment | >A oboInOwl:hasDbXref SPLIT=\|

@shawntanzk will manually curate values  - using PRO IDs (as curies) to cover expression of markers that nodes are named for.

**Comment by hkir-dev** [comment]
related [template](https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/templates/CCN202002013_class.tsv) updated.
