### ISSUE TITLE
Create and curate an Allen_marker table under /markers

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#89]
markers/{taxonomy_id}_Allen_markers.tsv

Taxonomy_node_ID | clusterName | Markers
-- | -- | --

See https://github.com/obophenotype/brain_data_standards_ontologies/issues/54#issuecomment-805092468 for discussion curation.

This will be used as input into DOSDP (allen_markers var - see #90)

**Comment by shawntanzk** [comment]
Added it here: 
https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/markers/CS202002013_Allen_markers.tsv

The following markers were not present in the fireplot:
Pdlim5 
Slc35d3
Myh8
Crhr2
Calb2
C1ql3
Th
Reln
Rspo1
Pld5
Slc7a10

The following produce little of marker but present: 
VIP Sncg barely expresses Sncg
Vip Serpinf1 barely expresses Serpinf1 
Vip C1ql1 barely expresses C1ql1 

Pvalb Vipr2_1 does not seem to express Vipr2 (I've put at # on the expression curation at the moment)

**Comment by jeremymiller** [comment]
Here is a fireplot of marker genes, with the ones above added.
![marker_fire_plot2](https://user-images.githubusercontent.com/25486679/117335816-6a5c9080-ae50-11eb-9bfd-7893d4993283.png)

**Comment by shawntanzk** [comment]
Thanks heaps @jeremymiller :) really appreciate it!

**Comment by shawntanzk** [comment]
@jeremymiller so sorry to have to ask again, but realised I did not check the MET type marker names. Could you help me add CCK to the marker list for a fireplot please? thanks so much in advance and sorry for the trouble

**Comment by jeremymiller** [comment]
This includes CCK and some other genes.  

![scrattch_plot_with_CCK](https://user-images.githubusercontent.com/25486679/118155946-a3a37c00-b3cd-11eb-946e-f4cab6f3ff69.png)

**Comment by shawntanzk** [comment]
Thanks so much @jeremymiller :) really appreciate it!
