### ISSUE TITLE
X - like classes schema

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#91]
The problem:

When we classify neurons using transcriptomics data, marker gene expression for some leaf nodes sometimes doesn't match the markers names in grouping classes.  

e.g. 

![image](https://user-images.githubusercontent.com/112839/117179642-3ab77500-adcb-11eb-986d-966d474b900d.png) ![image](https://user-images.githubusercontent.com/112839/117179508-18bdf280-adcb-11eb-9e1c-97e1921f70bc.png) ![image](https://user-images.githubusercontent.com/112839/117179549-25dae180-adcb-11eb-9ffe-219b2b1fca58.png)

alpha7 Egln3-1 has very low Lamp5 expression in a very small fraction of cells in the cluster used to define it.

Proposed solution:  Add x-like classes, e.g. LAMP5-like GABAergic interneuron of mouse primary motor cortex.  These _must_ be defined by a link to reference data and so belong (at least for now) in the BDS ontology.  Main difficulty: How can we roll IRIs for them?

We retain the `LAMP5 GABA-ergic` class in the ontology - relying on assertion of marker expression and auto-classification to populate. 

This may mean tweaking defs & labels of some grouping classes in CL - e.g. Lamp5 alpha7 GABAergic -> alpha7 GABAergic

**Comment by dosumis** [comment]
@shawntanzk  - can you review.  - trying to summarise our discussion today.

**Comment by shawntanzk** [comment]
To do:
- [ ] @shawntanzk to go through grouping classes and find those that fall under the above issue and change accordingly (includes label, defs, removing expresses)- see #54 for heatmap/fireplot as reference 
- [ ] Figure out IRIs for BDS ontology and add LAMP5-like and VIP-like
- [ ] Curate appropriate dendrogram nodes (eg node for LAMP5 now becomes LAMP5-like IRI)

**Comment by shawntanzk** [comment]
Currently (at least in my opinion), only Lamp5 and Vip has a few leaf nodes that don't seem to be expressing above baseline levels of their respective names. I've used the fireplot for judgement calls as I think it gives a better representation of expression. Below I've written about them: 

A7 cells - Elgn3_1: low levels of Lamp5 (more like a lamp5-like than a lamp5) -> I will make the change in CL together with the move-extended-description branch 

Vip Serpinf1_3 (and to an extend Vip Serpinf1_2) - low levels of Vip (part of L5/6 CCK cell) -> they techincally still express Vip, and Vip Serpinf1_1 has high level of Vip, so I think it is ok to keep it as it is in CL (expresses some Vip) - Perhaps a comment would be useful? However, given how Jeremy's table is not published, there is not citation to this. Given it's just one/two leaf node, perhaps a comment in BDS ontology would solve this? 

Vip Igfbp6_1  - low levels of Vip. Part of ??? Vip which for the ??? Part has harder issues than this anyway 

Not sure if this is an issue but Sncg Col14a1 and Sncg Npy2r has decently high Vip too 
Sncg Slc17a8 also has slightly low levels of Sncg but it seems to me clearly higher than baseline

**Comment by jeremymiller** [comment]
I think the "??? Vip" is now called "Uncharacterized VIP".  It is probably safe to ignore them.  If I am remembering correctly, those were cells that could not be found via Patch-seq (but please confirm).

**Comment by dosumis** [comment]
Will be discussed in nomenclature breakout.
